### ISSUE TITLE
tailwind start not working

### ISSUE THREAD

**Issue by Tobi-De** [timonweb/django-tailwind#102]
After initializing the theme app and installing the dependencies, I tried ```python manage.py tailwind start``` and I got this:

```sh
> theme@2.2.1 start
> npm run dev


> theme@2.2.1 dev
> nodemon -x \"npm run dev:sync\" -w tailwind.config.js -w postcss.config.js -w bs.config.js -e js

[nodemon] 2.0.13
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): tailwind.config.js postcss.config.js bs.config.js
[nodemon] watching extensions: js
[nodemon] starting `"npm run dev:sync"`
sh: 1: npm run dev:sync: not found
[nodemon] failed to start process, ""npm" exec not found
[nodemon] Error
    at Bus.<anonymous> (/home/tobidegnon/Documents/Python/goeat/goeat/theme/static_src/node_modules/nodemon/lib/nodemon.js:158:25)
    at Bus.emit (events.js:327:22)
    at ChildProcess.<anonymous> (/home/tobidegnon/Documents/Python/goeat/goeat/theme/static_src/node_modules/nodemon/lib/monitor/run.js:190:11)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)

```
but when I use the --no-sync option it works  fine, any idea to help ?
I tried setting NPM_BIN_PATH but the issue persist

**Comment by timonweb** [comment]
Hmm, could you change this line https://github.com/timonweb/django-tailwind/blob/23c6e27f449d92a704b40c17b8c1addefcda01ce/src/tailwind/app_template_v2/%7B%7Bcookiecutter.app_name%7D%7D/static_src/package.json#L13 in your 'package.json' to:

```
"dev": "nodemon -x 'npm run dev:sync' -w tailwind.config.js -w postcss.config.js -w bs.config.js -e js",
```

_Replaces `\"` with `'`._

And let me know if this has solved the issue.

**Comment by Tobi-De** [comment]
> Hmm, could you change this line in your `package.json`
> 
> https://github.com/timonweb/django-tailwind/blob/23c6e27f449d92a704b40c17b8c1addefcda01ce/src/tailwind/app_template_v2/%7B%7Bcookiecutter.app_name%7D%7D/static_src/package.json#L13
> 
> to:
> ```
> "dev": "nodemon -x 'npm run dev:sync' -w tailwind.config.js -w postcss.config.js -w bs.config.js -e js",
> ```
> 
> _Replaces `\"` with `'`._
> 
> And let me know if this has solved the issue.

yep it works
