### ISSUE TITLE
[BUG] Installation on Windows

### ISSUE THREAD

**Issue by creyD** [timonweb/django-tailwind#103]
I am encountering a bug in the installation process in Windows. When trying to `python manage.py tailwind install` it says 

```
CommandError: 
It looks like node.js and/or npm is not installed or cannot be found.

Visit https://nodejs.org to download and install node.js for your system.

If you have npm installed and still getting this error message, set NPM_BIN_PATH variable in settings.py to match path of NPM executable in your system.

Example:
NPM_BIN_PATH = "/usr/local/bin/npm"
```

Even though npm is installed and can be accessed via `npm` in the same shell.

I tried:
- Restarting
- Switching to macOS (works)
- Adding NPM_BIN_PATH with \\ , / and \ as dividers and %20 as space sign
- Switching consoles from PowerShell and CMD

**Comment by tazahmd** [comment]
Are you facing the issue?

**Comment by Hectoronian** [comment]
I'm facing this issue related to using Django, however, this project doesn't even have `settings.py`

**Comment by Hectoronian** [comment]
> I'm facing this issue related to using Django, however, this project doesn't even have `settings.py`

In my case I solved it, they were indeed using` settings.py `but with another name, `base.py`, and added the NPM_BIN_PATH

**Comment by Kingsoglobaltech** [comment]
am facing same issue please help

**Comment by Himani117** [comment]
> > Try this code, it worked in my project
> > NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"
> 
> In my case it's r'C:\Users\Me\AppData\Roaming\npm'. And settings it via NPM_BIN_PATH doesn't help at all.

Here I used your way to solve it, and it was done
