### ISSUE TITLE
Changes within styles.css only available after ./manage.py collectstatic

### ISSUE THREAD

**Issue by philipptrenz** [timonweb/django-tailwind#104]
Hey there @timonweb,

many thanks for your great plugin, I'm really enjoying the tailwind experience in Django!

Pretty sure I'm missing something, but this is my issue:
I'm running tailwind in `JIT` mode and `static/css/dist/styles.css` gets updated just fine. Nevertheless, although running Django via `./manage.py runserver` the changes within the CSS file only get available after doing `./manage.py collectstatic`. This is somewhat contrary to the idea of the JIT compiler in the development process. 

Do I need to explicitly add the static folder to `urlpatterns` in `urls.py` for development? Thanks a lot!

**Comment by timonweb** [comment]
Sorry, not sure what causing this. Try to add and see if helps.
