### ISSUE TITLE
NPM_BIN_PATH cookiecutter-django node

### ISSUE THREAD

**Issue by adammakowskidev** [timonweb/django-tailwind#106]
Hi
Im trying to use django-tailwind 
I use Django Cookiecutter with node docker image
I have a problem with the location NPM_BIN_PATH
Does anyone know how to point to the correct location for node docker image?

```
CommandError: 
It looks like node.js and/or npm is not installed or cannot be found.

Visit https://nodejs.org to download and install node.js for your system.

If you have npm installed and still getting this error message, set NPM_BIN_PATH variable in settings.py to match path of NPM executable in your system.

Example:
NPM_BIN_PATH = "/usr/local/bin/npm"
```

**Comment by timonweb** [comment]
ssh into the cookiecutter docker container, then run `which npm` command in the context of the container, it'll show you the npm path.
