### ISSUE TITLE
Cache Busting

### ISSUE THREAD

**Issue by lukeoiler** [timonweb/django-tailwind#108]
Hi,

I was wondering if there would be a good way to get around cache-busting in an automatic fashion. Because the Stylesheet-Name is generally static, if there are changes, the client will only see them once the caching is gone. I tried to integrate Post-CSS hash or Cache-Busting but couldn't make it work. Is there a way around it or a way to integrate it?

Best,
Lukas

**Comment by timonweb** [comment]
The simplest approach is to use `v=` parameter: https://django-tailwind.readthedocs.io/en/latest/templatetags.html#asset-versioning

Alternatively, you could wrap your stylesheet link with `{% compress css %}` tag from https://django-compressor.readthedocs.io/en/stable/, it'll do versioning automatically.

**Comment by lukeoiler** [comment]
Yea I tried django-compressor, but somehow I had some issues on chrome then where it wouldn't show the ring effect. Might be some installation issue on my side. But I completly missed the versioning, thank you so much for the quick help! That already gives me a working start, while I try to fix the compressor issue.

Thanks also again for this awesome repository!
