### ISSUE TITLE
styles.css not updating when running in docker

### ISSUE THREAD

**Issue by roushikk** [timonweb/django-tailwind#109]
I have a tailwind service in my docker-compose.yml with the following command:
`command: "python manage.py tailwind start"`

For some reason, it does not update the styles.css
But if I exec into the same container and then manually run the same command, it does update the file

Here are the logs of the command running using docker-compose:
```
> theme@2.2.1 dev:sync

> run-p dev:tailwind sync



> theme@2.2.1 sync

> browser-sync start --config bs.config.js



> theme@2.2.1 dev:tailwind

> cross-env NODE_ENV=development tailwindcss --postcss -i ./src/styles.css -o ../static/css/dist/styles.css -w


[Browsersync] Watching files...
```

And here are the logs when I use exec to run the same command on the same container:
```
> theme@2.2.1 dev:sync
> run-p dev:tailwind sync


> theme@2.2.1 dev:tailwind
> cross-env NODE_ENV=development tailwindcss --postcss -i ./src/styles.css -o ../static/css/dist/styles.css -w


> theme@2.2.1 sync
> browser-sync start --config bs.config.js

[Browsersync] Watching files...

warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.

Rebuilding...
Done in 307ms.
[Browsersync] File event [change] : ../static/css/dist/styles.css

```

**Comment by trey** [comment]
I've run into the same issue, but I think I've managed to get things working how I want without strictly following the example in this repo. I've just added a new port to the `service` where I have my Django app running (and haven't added a separate `tailwind` one. The only change to that file for me is adding the `8383` port setting:

```yaml
ports:
  - '127.0.0.1:8000:8000'
  - "8383:8383"
```

Then I can just run…

```shell
docker-compose exec web python manage.py tailwind start
```

…manually when I want to work on styles. The plus side of this is there's nothing in my `docker-compose.yml` that I need to ignore or bypass in production.

**Comment by pvanliefland** [comment]
On my end, setting `tty` to `true` in the tailwind service in `docker-compose.yaml` solves the issue (see #115 ).

**Comment by roushikk** [comment]
> On my end, setting `tty` to `true` in the tailwind service in `docker-compose.yaml` solves the issue (see #115 ).

Thank you so much for this solution. Adding `tty: true` fixed this issue for me

**Comment by timonweb** [comment]
@pvanliefland thank you so much for the fix! I had been banging my head against the wall and not understanding why it had started failing. Uff, that's the real power of the open-source!

**Comment by trey** [comment]
Is there a standard way of then not running that `service` in production?

**Comment by roushikk** [comment]
> Is there a standard way of then not running that `service` in production?

Yes, there is.
You usually have a base `docker-compose.yml` file and you extend it for different environments like dev, staging and production.

So, you'll have a base `docker-compose.yml` file without the tailwind service and then you'll have a `docker-compose.dev.yml` in which you'll add the tailwind service.

Official Docker documentation: https://docs.docker.com/compose/extends/

**Comment by trey** [comment]
> Yes, there is.

Thank you, @roushikk! I'm still a Docker noob in many ways. Thanks for showing me a better way! 😃
