### ISSUE TITLE
NPM_BIN_PATH at window not working

### ISSUE THREAD

**Issue by sutin1234** [timonweb/django-tailwind#11]
NPM_BIN_PATH at the window not working please make sample for me

**Comment by edgarmacas** [comment]
this worked for me
`# CONFIG TAILWIND NPM executable path configuration ONLY WINDOWS

NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"`

**Comment by timonweb** [comment]
@edgarmacas thank you for the tip, I'll add it to `README.md`.

**Comment by vanigupta20024** [comment]
This still does not work for me!

I added:
`NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"`

Error:
```
CommandError: 
It looks like node.js and/or npm is not installed or cannot be found.

Visit https://nodejs.org to download and install node.js for your system.

If you have npm installed and still getting this error message, set NPM_BIN_PATH variable in settings.py to match path of NPM executable in your system.      

Example:
NPM_BIN_PATH = "/usr/local/bin/npm"
```

I have installed nodejs and is running fine.

**Comment by vanigupta20024** [comment]
After having the same error and nothing working, this worked for me:

`NPM_BIN_PATH = r"C:\Program Files (x86)\nodejs\npm.cmd"`
