### ISSUE TITLE
[BUG] TypeError: handle_init_command() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by Ambro17** [timonweb/django-tailwind#111]
When running `python manage.py tailwind init app` the comand fails with
```
TypeError: handle_init_command() takes 1 positional argument but 2 were given
``` 
because it passes two arguments to `handle_init_command`.

I stopped the debugger there and one can see the two options
```python
        getattr(self, "handle_" + labels[0].replace("-", "_") + "_command")(
            *labels[1:],  # ('init', 'app') 
            **options, # {'verbosity': 1, 'settings': None, 'pythonpath': None, 'traceback': False, 'no_color': False, 'force_color': False, 'skip_checks': False, 'no_sync': False, 'no_jit': False, 'no_input': False, 'app_name': None}
        )
```
so the following method fails
```python
    def handle_init_command(self, **options):
        ...
```
Removing the labels argument works and the theme app is created as expected

Is this a recent regression? If i understand the problem correctly, all methods will face the same problem as they only expect `self` and `**kwargs` but no positional arguments received by `*labels[1:]`

# Project Layout
```
.
├── README.md
├── djtail
│   ├── djtail
│   │   ├── __init__.py
│   │   ├── asgi.py
│   │   ├── settings.py
│   │   ├── urls.py
│   │   └── wsgi.py
│   ├── manage.py
│   └── tailwind.config.js
├── poetry.lock
├── pyproject.toml
├── static
│   └── tailwind.css
```
# Software versions
```
Python 3.9.7
Django 3.2.9
Django-tailwind 2.2.2
```

Thank you for the project, let me know if i can add more information or test an alternative branch

**Comment by roushikk** [comment]
According to the [documentation](https://django-tailwind.readthedocs.io/en/latest/installation.html), you need to run `python manage.py init` (without the app name), and it'll ask you for the app name later.
I don't think there's support for passing the app name directly in the `manage.py tailwind init`  command. However, the support can be added with a few tweaks

**Comment by Ambro17** [comment]
Oh, i copied the command from a tutorial and assumed it was correct, i will try without it and report back
