### ISSUE TITLE
Not working on Django version 3.0.8 - Update Documentation

### ISSUE THREAD

**Issue by victormachadogp** [timonweb/django-tailwind#113]
Did not work on my Django version 3.0.8 project, actually whenever I run the command `python -m pip install django-tailwind` it works, but in the process it would uninstall my version of Django and install Django 4.0.

And as the project has been around for a while, this version of Django unfortunately  doesn't work.

I looked in the documentation for any hints about this process but I couldn't find it.
I think it would be interesting to have a description or a warning about this process of uninstalling and installing a newer version of Django in the documentation.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/44147653/145595769-8eee685d-6ab2-4146-8dac-4e90e6e3f3d0.png">

Anyway, I tested it on a newer Django project and it worked fine, great package!!

**Comment by timonweb** [comment]
Shoot, I bumped minimal Django version by mistake. Fixing soon, thanks for reporting!

**Comment by justinmayer** [comment]
@timonweb: Glad to hear it. It seems that as of https://github.com/timonweb/django-tailwind/commit/7893ecd824419dbded3126552e4c5428196ccba0 Django 4.0+ is now required. Would be great to loosen that!

**Comment by timonweb** [comment]
Pushed the `3.0.1` version, it loosens requirement back to the `2.2`.
