### ISSUE TITLE
python manage.py tailwind start not working 

### ISSUE THREAD

**Issue by ebanhamhall** [timonweb/django-tailwind#114]
Hi,

Running this on Windows.

When I run the `python manage.py tailwind start` command the localhost server doesn't start. It also doesn't work when I tried `python manage.py tailwind start --no-sync`

I've tried following the instructions in Issue 102, https://github.com/timonweb/django-tailwind/issues/102 but unfortunately that don't work for me. I get the following:

> theme@3.0.0 start
> npm run dev

> theme@3.0.0 dev
> nodemon -x 'npm run dev:sync' -w tailwind.config.js -w postcss.config.js -w bs.config.js -e js

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): tailwind.config.js postcss.config.js bs.config.js
[nodemon] watching extensions: js
[nodemon] starting `'npm run dev:sync'`
''npm' is not recognized as an internal or external command,
operable program or batch file.
[nodemon] app crashed - waiting for file changes before starting...

**Comment by ritznotcrackers** [comment]
Hello, I hope I can help. The error says 

```bash
npm is not recognized as an internal or external command, operable program or batch file
```
Do you have [Node.js](https://nodejs.org/en/) installed on your computer? If not, go ahead an install it. If you have Node.js installed maybe it is not added in your environment variables. 

Lastly, maybe you forgot to add the configuration path to the `npm` executable. Open `settings.py` and add the line below, or you can refer to this [link](https://django-tailwind.readthedocs.io/en/latest/installation.html) for more details.

```python
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"
```

**Comment by ebanhamhall** [comment]
Thanks for taking a look.

I tried all this but still had issues opening the site on my local machine.

In the end the thing that fixed it was running `python manage.py tailwind start` in one terminal, then opening a **second** terminal and running `python manage.py runserver`. This got things up and running quite happily for me and I'm happily coding with Django and Tailwind now.

Best,

Ed

**Comment by baytech77** [comment]
This is very helpful
