### ISSUE TITLE
Adding classes from JavaScript or jQuery

### ISSUE THREAD

**Issue by matiszz** [timonweb/django-tailwind#116]
I'm making my landing page with `django-tailwind`. I want to add some behavior such as, when a user clicks a button, it changes its color, and I'm doing that with jQuery:
```js
$('#action_button_1').click(function (e) {
    $('#action_button_1').attr('class', 'mx-auto text-gray-300 font-bold rounded py-2 px-4 w-44 bg-lime-300')
})
```
But styles don't seem to apply. I can see it rendered the classes correctly by inspecting the element, but all styles disappear.

Is this a known bug? I've tried using Tailwind CDN and it works as expected, but it doesn't work with `{% tailwind_css %}`

<details>
  <summary>My base.html file</summary> 
  
  ```html
  {% load static tailwind_tags %}

  <!DOCTYPE HTML>
  <html lang="en">
  <head>
      {% block head %}
          ...
          {% tailwind_preload_css %}
          {% tailwind_css %}
      {% endblock %}
  </head>
  ```
</details>

**Comment by matiszz** [comment]
Any updates on this? Am I doing something wrong or is this an actual bug?

**Comment by roushikk** [comment]
You need to enable JS support first.
Open  `theme/static_src/tailwind.config.js` and uncomment the following lines in the `purge` array:
```
        /**
         * JS: If you use Tailwind CSS in JavaScript, uncomment the following lines and make sure
         * patterns match your project structure.
         */
        /* JS 1: Ignore any JavaScript in node_modules folder. */
        // '!../../**/node_modules',
        /* JS 2: Process all JavaScript files in the project. */
        // '../../**/*.js',
```

You may need to change the pattern to make it work with your project structure.

**Comment by roushikk** [comment]
Refer to this: https://django-tailwind.readthedocs.io/en/latest/installation.html#content-formerly-purge-rules-configuration

You need to include js files

**Comment by matiszz** [comment]
Completely right. Sorry for the inconvenience. I hope this is useful for someone else in the future!

**Comment by timonweb** [comment]
@roushikk thanks for the help!
