### ISSUE TITLE
Compatibility with django-browser-reload?

### ISSUE THREAD

**Issue by hirusi** [timonweb/django-tailwind#117]
The phenomenal Adam had released https://github.com/adamchainz/django-browser-reload a while ago. Any ideas on how these two can work together?

**Comment by timonweb** [comment]
Yes, I'm working on this. Encountered an issue and reported it [here](https://github.com/adamchainz/django-browser-reload/issues/46). Hope I'll have more info soon.

**Comment by timonweb** [comment]
FYI, just opened a draft PR: https://github.com/timonweb/django-tailwind/pull/119
