### ISSUE TITLE
Unable to find npm even when setting NPM_BIN_PATH in settings on Windows 

### ISSUE THREAD

**Issue by Antsthebul** [timonweb/django-tailwind#121]
The directory that has **npm** is set in PATH. Following the instructions , https://django-tailwind.readthedocs.io/en/latest/installation.html#step-by-step-instructions , I was getting the error that node/npm was not installed when running `python manage.py tailwind install`. The only way I was able to sucessfully install Tailwind's dependencies was by updating the call `subprocess.run()` *tailwind/npm.py*

`            subprocess.run(["cmd", "/c", self.npm_bin_path] + list(args), cwd=self.cwd)
` 

This is also assuing the string path to NPM was also correctly relating to the OS being used
`NPM_BIN_PATH="C:\\Program Files\\nodejs\\npm"`
Not sure if my setup is configured incorrectly or if this could be helpful

**Setup**
Windows 10 (using powershell)
Python==3.10.0
django-tailwind==3.1.1
django==4.0.1

**Comment by curtisim0** [comment]
Hey @Antsthebul 

Maybe the `NPM_BIN_PATH` is something else than what is listed in the docs?

I think in Windows you can use `which npm` and it would print the path to your NPM executable. You can compare the output of your `which npm` to the given `"C:\\Program Files...etc"` in the docs. I would bet it's different.

Hopefully, that helps!

===

For those using Linux, `whereis npm` will show you the path to your npm.

**Comment by Antsthebul** [comment]
Well for some reason when I run which NPM I get  something similiar except its prefixed with `/cygdrive/..`. But anway, right after I posted this, I found the regex with the .cmd notation, and it worked. Im sorry but I thank you for the quick response. 

If possible, maybe you can help me with 2 more things. Im getting a 404 dist/styles.css not found, Does that mean, even in dev mode, I need to run the build command 1st and then modify the .css in `static_src`? And also is the `--postcss -i` flag mean I must only use the `styles.css` within *theme/static_src/src*? Thanks again for all your help, I was just confused on the project structure with tailwin integrated.
