### ISSUE TITLE
Asset versionning

### ISSUE THREAD

**Issue by Valentinmf** [timonweb/django-tailwind#122]
Since latest version of django-tailwind 3.1.1 I have to put {% tailwind_css v='3' %} to get the tailwind working properly, is that normal ?

**Comment by timonweb** [comment]
We don't handle automatic asset versioning. It's a job of your asset pipeline. I usually use Django-Tailwind with [django-compressor](https://django-compressor.readthedocs.io/en/stable/) and it handles versioning nicely. As an escape hatch, there's the `v=` parameter of the tag. More info in the docs: https://django-tailwind.readthedocs.io/en/latest/templatetags.html#asset-versioning
