### ISSUE TITLE
Leveraging new standalone CLI

### ISSUE THREAD

**Issue by marianhlavac** [timonweb/django-tailwind#123]
Last year, Tailwind introduced standalone CLI, which doesn't require Node environment to be installed.  
More at https://tailwindcss.com/blog/standalone-cli

I don't feel comfortable forcing Python developers to spin up the Node environment, but this might help to get rid of the requirement.

Is there any interest in replacing npm calls with CLI calls?

**Comment by timonweb** [comment]
Sure, there's an option. I even created a package for exactly this purpose: https://github.com/timonweb/pytailwindcss You can go ahead and try it instead of npm and see how it works. When I get enough time, I'll integrate it with `django-tailwind`.
