### ISSUE TITLE
JIT not working inside docker container

### ISSUE THREAD

**Issue by TobySuch** [timonweb/django-tailwind#126]
Hi, forgive me if this isn't a supported use case for this package. I am trying to get this running inside a docker container where my development server is running. I stumbled upon #63 in order to get this working. However it doesn't appear to be working.

I have a rundev.sh script which runs the `python manage.py tailwind start &` before starting the Django dev server. I can see in the logs that this process does start, however it never appears to generate the css file. I can attach a shell to the container and I can confirm the process is not running.

rundev.sh:

    #!/bin/sh

    set -o errexit
    set -o pipefail
    set -o nounset
    set -o xtrace

    python manage.py tailwind start &
    python manage.py runserver 0.0.0.0:8000

Startup log:

    shifter-web-1  | Waiting for postgres...
    shifter-web-1  | PostgreSQL started
    shifter-web-1  | Operations to perform:
    shifter-web-1  |   Apply all migrations: admin, auth, contenttypes, sessions, shifter_auth
    shifter-web-1  | Running migrations:
    shifter-web-1  |   No migrations to apply.
    shifter-web-1  |
    shifter-web-1  | up to date, audited 128 packages in 749ms
    shifter-web-1  |
    shifter-web-1  | 23 packages are looking for funding
    shifter-web-1  |   run `npm fund` for details
    shifter-web-1  |
    shifter-web-1  | found 0 vulnerabilities
    shifter-web-1  |
    shifter-web-1  | > theme@3.1.1 start
    shifter-web-1  | > npm run dev
    shifter-web-1  |
    shifter-web-1  |
    shifter-web-1  | > theme@3.1.1 dev
    shifter-web-1  | > cross-env NODE_ENV=development tailwindcss --postcss -i ./src/styles.css -o ../static/css/dist/styles.css -w
    shifter-web-1  |
    shifter-web-1  | Superuser created successfully.
    shifter-web-1  | + python manage.py runserver 0.0.0.0:8000
    shifter-web-1  | Watching for file changes with StatReloader
    shifter-web-1  | Performing system checks...
    shifter-web-1  |
    shifter-web-1  | System check identified no issues (0 silenced).
    shifter-web-1  | February 13, 2022 - 00:03:35
    shifter-web-1  | Django version 4.0.2, using settings 'shifter.settings'
    shifter-web-1  | Starting development server at http://0.0.0.0:8000/
    shifter-web-1  | Quit the server with CONTROL-C.
    shifter-web-1  | [13/Feb/2022 00:09:14] "GET / HTTP/1.1" 200 593
    shifter-web-1  | [13/Feb/2022 00:09:14] "GET /static/css/dist/styles.css HTTP/1.1" 200 14779
    shifter-web-1  | Not Found: /favicon.ico
    shifter-web-1  | [13/Feb/2022 00:09:14] "GET /favicon.ico HTTP/1.1" 404 2272

No process running:

    /app # ps -a
    PID   USER     TIME  COMMAND
        1 root      0:00 {rundev.sh} /bin/sh /app/rundev.sh
      65 root      0:00 python manage.py runserver 0.0.0.0:8000
      66 root      0:06 /usr/local/bin/python manage.py runserver 0.0.0.0:8000
      74 root      0:00 sh
      125 root      0:00 ps -a

Curiously if I run the command from the shell it does appear to run, and it does generate the css file. But while the command never terminates, further changes to the source files do not trigger it to rebuild the css files.

Manual run:

    /app # python manage.py tailwind start

    > theme@3.1.1 start
    > npm run dev

    > theme@3.1.1 dev
    > cross-env NODE_ENV=development tailwindcss --postcss -i ./src/styles.css -o ../static/css/dist/styles.css -w

    Module dependencies: 9.12ms

    Rebuilding...
    Creating context: 236.25ms
    Reading changed files: 2.323ms
    Generate rules: 7.42ms
    Build stylesheet: 0.467ms
    Potential classes:  90
    Active contexts:  0
    Compiling CSS: 261.433ms
    Done in 376ms.
    Finished in: 378.191ms

Additionally to this, if I change the command inside `package.json` file to remove the `-w` argument, it does run on startup and generate the css, however this obviously won't recreate the CSS files in a JIT fashion anymore. This leads me to think there is an issue with the "watch" part (probably with the tailwind node application). Any ideas for workarounds for this issue?

**Comment by karl1k** [comment]
Are you running the docker container on Windows?
I have pretty much this exact same issue, although I'm using a docker-compose config very similar to [example/docker-compose.yml](https://github.com/timonweb/django-tailwind/blob/master/example/docker-compose.yml).

When running the containers on Windows the css file is only generated at startup, the watch process doesn't seem to register file changes, and I haven't found any fix or workaround for this yet...

But when running it on my Linux laptop everything works perfectly fine, the css is rebuilt as soon as I make a change in one of the files listed in the content field in tailwind.config.js

**Comment by TobySuch** [comment]
@karl1k Thanks for the tip! Just tried it on Linux and although it still doesn't seem quite right for me, I can run the script manually and it will pick up on the changes. Will go through my config again when I get a chance and see if I can get it fully working.

Wonder if the bug is with Docker or Node?

**Comment by karl1k** [comment]
Turns out it's a limitation of docker on WSL2: "Linux containers only receive file change events (“inotify events”) if the original files are stored in the Linux filesystem. For example, some web development workflows rely on inotify events for automatic reloading when files have changed." (https://docs.docker.com/desktop/windows/wsl/)

**Comment by TobySuch** [comment]
Thanks for the info @karl1k, between that and the example docker-compose file which I didn't see before I should be able to get this working myself. Obviously not an issue with this package so will close the issue. Cheers!
