### ISSUE TITLE
Cannot install TailWind for Wagtail

### ISSUE THREAD

**Issue by dqcuong93** [timonweb/django-tailwind#129]
When running this command: "python manage.py tailwind install".
I met this error: "ModuleNotFoundError: No module named 'tailwind_themewagtail'".

Please help, thank you.

**Comment by buhosiliscodirococo** [comment]
Did you try putting "tailwind_themewagtail" in INSTALLED_APPS[] ?

I have an identical problem, only that I have that error when moving "theme" to another directory to have a more organized tree

**Comment by karl1k** [comment]
@dqcuong93 
Did you generate the theme app with "tailwind init tailwind_themewagtail'" prior to running "tailwind install"? Or did you run "tailwind init" and manually renamed the app to "tailwind_themewagtail"?

Do you have this in your settings.py?
```
INSTALLED_APPS = [
  ...
  'tailwind',
  'tailwind_themewagtail'
]
TAILWIND_APP_NAME = 'tailwind_themewagtail''
```
I'm using Wagtail and simply intalled django-tailwind following the instructions in the docs ([Installation guide](https://django-tailwind.readthedocs.io/en/latest/installation.html#step-by-step-instructions)).
If you post your settings.py, apps.py for the theme app and your project layout with something like "tree -L 2" maybe I'll be able to help. 

@buhosiliscodirococo 
After moving the theme app did you update the app name in apps.py? I keep all my apps under the project root, but if you have apps in other folders I think you need to change it to `name = 'appsDirectory.appName'` and register it in INSTALLED_APPS with the same name.

**Comment by dqcuong93** [comment]
> @dqcuong93 Did you generate the theme app with "tailwind init tailwind_themewagtail'" prior to running "tailwind install"? Or did you run "tailwind init" and manually renamed the app to "tailwind_themewagtail"?
> 
> Do you have this in your settings.py?
> 
> ```
> INSTALLED_APPS = [
>   ...
>   'tailwind',
>   'tailwind_themewagtail'
> ]
> TAILWIND_APP_NAME = 'tailwind_themewagtail''
> ```
> 
> I'm using Wagtail and simply intalled django-tailwind following the instructions in the docs ([Installation guide](https://django-tailwind.readthedocs.io/en/latest/installation.html#step-by-step-instructions)). If you post your settings.py, apps.py for the theme app and your project layout with something like "tree -L 2" maybe I'll be able to help.
> 
> @buhosiliscodirococo After moving the theme app did you update the app name in apps.py? I keep all my apps under the project root, but if you have apps in other folders I think you need to change it to `name = 'appsDirectory.appName'` and register it in INSTALLED_APPS with the same name.

Thank you for helping me, now I don't have that instance but definitely will try again with your advice.
