### ISSUE TITLE
how to make the class name completion work ?

### ISSUE THREAD

**Issue by Royleeother** [timonweb/django-tailwind#13]
Everything works fine on me rendering the tailwind css in my Django project. But when I type the classname the IDE would not show the options to make completion work. I did install a _Tailwind CSS IntelliSense_ plugin in my VScode, it works fine in my official tailwind enviroment.
So is this _django-tailwind_ module not trigger the plugin ? Anyway, how to make to completion work.

**Comment by timonweb** [comment]
I think that's the IDE issue. I've never thought about that but I just fired vs code with a project that has django-tailwind and autocompletion works out of the box. Basically, if it works for vanilla tailwind, than it should work for django-tailwind too.
