### ISSUE TITLE
taiwind updating slowly or not updating at all

### ISSUE THREAD

**Issue by kris-slinger** [timonweb/django-tailwind#132]
My 'taiwind start' is working perfectly but its updating too slowly. Each time i enter a new utility class,it does'nt change at all or if it does change,its taking too long. What do you think is wrong?

**Comment by Alurith** [comment]
I have the same issue, no solution found yet.

**Comment by kris-slinger** [comment]
I solved by opening my project in different browsers

**Comment by kris-slinger** [comment]
i think it cached the css of the previous build,the best thing is to add hashcontext on all the css produced by taiwind
