### ISSUE TITLE
How to use TailwindCSS plugins (like DaisyUI)?

### ISSUE THREAD

**Issue by ddahan** [timonweb/django-tailwind#137]
Hello.

I browse the documentation and didn't find anything about plugins.
I'd like to use [daisy UI](https://daisyui.com/docs/install/) which usually need `npm` to be installed before configuring the `tailwind.config.js` file.

I'd like to use official Tailwind plugins likes Typography as well.

Is there a way to do that with django-tailwind?

Thanks.

**Comment by Alexandre-petitjean** [comment]
1. Move to the location of node_modules. For me ./theme/static_src/
2. Install the package with `npm i daisyui`
3. Add the plugin in tailwind.config.js

This should work with other tailwind plugin as well.

**Comment by abrichr** [comment]
Hello, unfortunately the above solution isn't working for me. I have django and django-tailwind installed, and I can apply tailwind classes, but not the daiysui classes. Here is the `theme/static_src/tailwind.config.js`:

```
module.exports = {
    content: [
        '../templates/**/*.html',
        '../../templates/**/*.html',
        '../../**/templates/**/*.html',
        '!../../**/node_modules',
        '../../**/*.js',
        '../../**/*.py'
    ],
    theme: {
        extend: {},
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
        require('@tailwindcss/line-clamp'),
        require('@tailwindcss/aspect-ratio'),
        require('daisyui'),
    ],
}
```

Any suggestions?
