### ISSUE TITLE
manage.py tailwind start hangs

### ISSUE THREAD

**Issue by kkinder** [timonweb/django-tailwind#138]
I'm experimenting with django-tailwind, but finding that tailwind start tends to hang:

```
$ ./manage.py tailwind start

> djangotest@3.1.1 start
> npm run dev


> djangotest@3.1.1 dev
> cross-env NODE_ENV=development tailwindcss --postcss -i src/styles.css -o ../static/css/dist/styles.css -w


Rebuilding...
Done in 126ms.
```

It never starts. ctrl+c quits fine, but it never seems to start the actual server. I am finding, however, that runserver works fine:

```
$ ./manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
May 16, 2022 - 16:12:59
Django version 4.0.4, using settings 'DjangoTest.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

Anything I should try?

Some basic system info:

- Python 3.8.9
- Django 4.0.4
- MacOS Monterey

**Comment by sudoer-zero** [comment]
Same Here.
system info:

- Python 3.10.5
- Django 3.2.3
- Archlinux

**Comment by timonweb** [comment]
@kkinder it's not going to start any server. It starts the watch command and judging by your output

```
Rebuilding...
Done in 126ms.
```

it's doing just fine. You need to run `python manage.py runserver` in a separate terminal to start actual Django server.
