### ISSUE TITLE
manage.py tailwind build exits with success even if command failed

### ISSUE THREAD

**Issue by mgax** [timonweb/django-tailwind#139]
In my Dockerfile I have this step: `RUN ./manage.py tailwind build` (followed by `./manage.py collectstatic`). The build completed successfully, but the image was broken, because it didn't contain the `static/css/dist` directory.

It took a while to figure out; ideally, if `manage.py tailwind build` fails, it should exit with an error, so that the whole image building fails.

The error was apparent from inside the Docker container; should have run `manage.py tailwind install` first:

```
$ ./manage.py tailwind build && echo ok

> theme@3.1.1 build
> npm run build:clean && npm run build:tailwind


> theme@3.1.1 build:clean
> rimraf ../static/css/dist

sh: 1: rimraf: not found
ok
```

**Comment by timonweb** [comment]
Indeed, added returncode `1` in `3.3.0`. Thanks for reporting.

**Comment by 2qxtx** [comment]
@mgax How did you resolve the original "rimraf: not found" error? My docker build fails as a result of this with the latest version of django-tailwind (3.4), while the previous version I was on (3.1.1) would simply overlook it.

**Comment by mgax** [comment]
@2qxtx I simply ran `./manage.py tailwind install`. It probably needs to install new versions of NPM dependencies after you do an upgrade.

**Comment by 2qxtx** [comment]
> @2qxtx I simply ran `./manage.py tailwind install`. It probably needs to install new versions of NPM dependencies after you do an upgrade.

Thank you for the quick reply. Unfortunately, this did not work for me. I also tried deleting my `package-lock.json` and `node_modules` folder, but to no avail.

**Comment by mgax** [comment]
@2qxtx I'm also on django-tailwind 3.4.0 and rimraf got installed alright. This is in a Docker image, so the `node_modules` is not left over from a previous version. Hope this helps:

```
wagtail@1f3f5a0f1cda:/app/theme/static_src$ ls -l node_modules/.bin/rimraf 
lrwxrwxrwx 1 wagtail wagtail 16 Sep 14 10:49 node_modules/.bin/rimraf -> ../rimraf/bin.js
wagtail@1f3f5a0f1cda:/app/theme/static_src$ pip freeze | grep tailwind
django-tailwind==3.4.0
wagtail@1f3f5a0f1cda:/app/theme/static_src$ grep rimraf package*
package-lock.json:        "rimraf": "^3.0.2",
package-lock.json:    "node_modules/rimraf": {
package-lock.json:      "resolved": "https://registry.npmjs.org/rimraf/-/rimraf-3.0.2.tgz",
package-lock.json:        "rimraf": "bin.js"
package-lock.json:    "rimraf": {
package-lock.json:      "resolved": "https://registry.npmjs.org/rimraf/-/rimraf-3.0.2.tgz",
package.json:    "build:clean": "rimraf ../static/css/dist",
package.json:    "rimraf": "^3.0.2",
```
