### ISSUE TITLE
Tailwind CSS rules not working with included files!

### ISSUE THREAD

**Issue by fspjonny** [timonweb/django-tailwind#143]
I can't say it's a bug, but I have this issue unresolved, but feel free to close this ticket if it's not a valid issue!

When I include pieces of HTML in my project, Tailwind's CSS rules are not working.

```
parts files are in STATICFILES_DIRS

{% extends 'base.html' %}
{% block title %}Task | List{% endblock %}
{% block header %}
    {% include 'parts/header.html' %}
{% endblock %}
...

```

But if I put the whole piece of code inside the "block header" tag, it works perfectly!

```
{% extends 'base.html' %}
{% block title %}Task | List{% endblock %}
{% block header %}
<div class="h-32 flex flex-wrap text-center content-center">
    <div class="bg-slate-300 mx-auto">
        <p class="text-3xl lg:text-5xl font-extrabold tracking-tight text-indigo-600 text-shadow">Django + Tailwind =
            ❤️😃❤️</p>
    </div>
</div>
{% endblock %}
...
```
To make this work across my entire project, I would need to put the same code snippet on every page.
This is not good, I broke the DRY principle. 
Is there any way to make this work using "{% inlude %}" ?

**Comment by nigelcopley** [comment]
off the top of my head, with the limited info, i would say you're not including your includes templates in the config https://django-tailwind.readthedocs.io/en/latest/installation.html#optional-configurations

**Comment by fspjonny** [comment]
>This is my base.html template for the others part page's.
![image](https://user-images.githubusercontent.com/36781832/178144500-2e2e2741-1884-4bbb-8a7b-4b663e10047e.png)
The another parts, are included or inherited throught the block tag template language, basically this is what i use.
Did you find something wrong with my structure?

**Comment by ddrake** [comment]
First of all, thanks for an excellent library!
Secondly, I think I might have some idea what's going on here...

A typical Django application structures template directories something like the following tree, where myapp is a Django app with its templates stored in myprojectdir/myapp/templates/myapp:

```
myprojectdir
├── LICENSE
├── myapp
│   ├── admin.py
│   ├── apps.py
│   ├── __init__.py
│   ├── migrations
│   ├── models.py
│   ├── templates
│   │   └── myapp
│   │        ├── base.html
│   │        └── index.html
│   ├── tests.py
│   ├── urls.py
│   └── views.py
├── manage.py
├── README.md
├── theme
│   ├── static_src
        └── tailwind.config.js
```

In this example, myprojectdir/myapp/templates/myapp has a base.html template and an index.html template that extends base.html, but for me, with the default tailwind.config.js, *only tailwind tags/styles that used in base.html were available in index.html*.  The default tailwind.config.js file looks something like this:

module.exports = {
    content: [
        /\*  Templates within theme app (<tailwind_app_name>/templates), e.g. base.html. */
        '../templates/\*\*/\*.html',
       /\* Main templates directory of the project (BASE_DIR/templates). \*/
        '../../templates/\*\*/\*.html',
        /\* Templates in other django apps (BASE_DIR/<any_app_name>/templates). \*/
        '../../\*\*/templates/\*\*/\*.html',
        ...
}

I added this (hardcoded) line to the file:
        '../../myapp/templates/myapp/*.html',

... and then I was able to get Tailwind styles in index.html that were not in base.html.

I don't really understand why that last pattern,  '../../\*\*/templates/\*\*/\*.html', with \*\* indicating any number of directories, didn't match --  Just letting you know what I saw.

Here's my (simplified) base.html:
{% load static tailwind_tags %}
```
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
      <title>IFBT</title>
    {% endblock %}
    <meta charset="UTF-8">
          ...
    {% tailwind_css %}
  </head>
  <body class="bg-gray-50 font-serif leading-normal tracking-normal">
    <div class="container mx-auto">
      <section class="flex items-center justify-center h-screen">
        {% block content %}
        {% endblock %}
      </section>
    </div>
  </body>
</html>
```

And here's my index.html:

```
{% extends 'myapp/base.html' %}
{% block content %}
<p class="text-green-400 text-3xl">Hello</p>
{% endblock %}
```

**Comment by ddrake** [comment]
In my case, this was caused by one of two things:

1. An error in a tailwind style tag or in the HTML.
2. The browser was *caching* my styles.css.  In Firefox, the cache can be cleared by \<ctrl\>+\<shift\>+R.  To verify whether or not this is your issue, you can compare the styles.css file in your browser tool (style editor > open in new tab) with the one in myprojectdir/theme/static/css/dist/.  Several times, I was adding new tailwind tags to included files which represented styles not in the base template, then seeing the tailwind tags appear correctly in the markup in the browser tool, but not seeing the correct generated css in the browser.
