### ISSUE TITLE
Classes not applying due browser cache

### ISSUE THREAD

**Issue by hamzaabde** [timonweb/django-tailwind#147]
When apply new classes to my html, the browser isn't applying them. After some digging, I figured out that output css is being cache by the browser. By the way, I am using chrome and tailwind tags to include in templates.

**Comment by Shittua1** [comment]
same here i am tried of the tailwind i use it in my project and working early but after some time it just stop working all the class that i am adding is not working only the class that i have use before and i am using tailwind for my clients work and i have to add some features to my website now. am very sad that it is not working again please you guys should please tell us what next or fixed the issue

**Comment by abrichr** [comment]
See https://github.com/timonweb/django-tailwind/issues/108 for possible solutions
