### ISSUE TITLE
Add support for yarn package manager

### ISSUE THREAD

**Issue by Meakelvis** [timonweb/django-tailwind#15]
I was hoping support for the Yarn Package Manager could be added as a way of expanding the reach and scope of the project. Thank you.

**Comment by timonweb** [comment]
Not planned as of now, sorry. I want to keep things as simple as possible here and everyone has and digs `npm` whereas `yarn` is an additional dependency and once you introduce it, you have to worry about both `npm` and `yarn`. Unfortunately, I don't have that much time.
