### ISSUE TITLE
Unknown command: `tailwind init`

### ISSUE THREAD

**Issue by celsiusnarhwal** [timonweb/django-tailwind#151]
Whenever I run `python manage.py tailwind init` I get an error reading `Unknown command: tailwind init`.  I also don't see `tailwind` in the output of `python manage.py help`. 

django-tailwind is installed in my environment (though via Poetry rather than pip, if that makes any difference) and included in my `INSTALLED_APPS`.

[The last person to have this issue](https://github.com/timonweb/django-tailwind/issues/58) unfortunately did not share their resolution to it.

Am I missing something?

**Comment by mgax** [comment]
@celsiusnarhwal not sure why it doesn't work for you; I've done an installation of Django and django-tailwind in a fresh repo, using Poetry, and it works fine.

Here is the repo, maybe it helps to compare with your setup: https://github.com/mgax/django-tailwind-setup

**Comment by celsiusnarhwal** [comment]
Thanks for the repo. I figured out what the issue was; my Django project was named "tailwind", which conflicted with the name of the `tailwind` app.
