### ISSUE TITLE
`django-tailwind` should not have a hard dependency on `django-browser-reload`

### ISSUE THREAD

**Issue by baseplate-admin** [timonweb/django-tailwind#162]
Hi there,

Thanks for creating this awesome package.

It seems that you have : https://github.com/timonweb/django-tailwind/blob/045c6dae75be0eb119b0a018b379a2ffb29fd034/pyproject.toml#L31

  as a hard dependency for `django-tailwind` but it should be noted that to run `django-tailwind` in production `django-browser-reload` is not required. `django-browser-reload` is very useful when **developing** a website..

What should we do here : 
1. Make the `django-browser-reload` optional for those who wants to install it with `django-tailwind`.  ( eg: `pip install django-tailwind[reload]` )
2. Provide a link in the docs to inform user on `django-browser-reload` but not bundle it.

Reasoning : 
1. It removes a package from venv and thereby reducing its size. Specially since some systems like [AWS Lambda has strict limit on `venv` size](https://stackoverflow.com/questions/56954585/what-are-the-possibilities-in-order-to-reduce-the-size-of-a-python-virtual-envir)
2. Code Reloading is not required in production.
3. Frees up memory ( by not loading `django-browser-reload` into memory )
4. Speeds up django ( because theres one less middleware )

Thanks for reading..

**Comment by dyspop** [comment]
I'm battling Reason 1 as we speak

**Comment by baseplate-admin** [comment]
Hi @timonweb,

Since the community actively wants this Feature, would you be willing to add this ?

**Comment by cafalchio** [comment]
Why not an optional feature?
