### ISSUE TITLE
Setting an item to not visible as the default then visible at any larger breakpoint doesn't work

### ISSUE THREAD

**Issue by dyspop** [timonweb/django-tailwind#164]
For example:
```
<div class="hidden sm:block sm:visible">This element is hidden on screens larger than small.</div>
```

This should be hidden at the smallest screen size but visible at `sm` and larger. 

The solution is to import tailwind screens in the static_src/src/styles.css (I will submit a PR)

**Comment by andrewedstrom** [comment]
@dyspop Thank you for identifying the fix! I was having the same issue, and updating `static_src/styles.css` in my project fixed it for me.
