### ISSUE TITLE
Changelog file is not updated. 

### ISSUE THREAD

**Issue by ERosendo** [timonweb/django-tailwind#177]
The `changelog` file doesn't have the list of notable changes for version 3.6 and I think there are a few updates worth mentioning. Here's an attempt:

```
## 3.6.0
- Adds support for Django 4.2.
- Stops caching CSS in DEBUG mode.
- Makes django-browser-reload dependency optional to install by using the [reload] extras.
- Adds instructions on how to contribute 
```

**Comment by timonweb** [comment]
@ERosendo indeed I missed that. Thanks for the text, updated!
