### ISSUE TITLE
Installation Error with "django-tailwind[reload]" Package

### ISSUE THREAD

**Issue by SergejSi** [timonweb/django-tailwind#178]
Hello,

I'm glad to hear that you're exploring Python and Django! It's great that you found a solution to the issue you encountered while installing the "django-tailwind[reload]" package.

After doing some research, you discovered that enclosing the package name in single quotes, like this: "pip install 'django-tailwind[reload]'", resolved the problem. This is an important detail that could be considered for inclusion in the package's documentation.

It's always helpful when documentation provides clear instructions and highlights any specific considerations, especially for newcomers to a particular framework or library. If you have any further questions or need assistance with Django or any other Python-related topics, feel free to ask. Happy coding!

**Comment by YDX-2147483647** [comment]
A simple note: The quotes are only required for some shells (e.g. zsh), not all (e.g. bash, PowerShell), according to https://github.com/pypa/packaging.python.org/issues/1209.

However I agree that `pip install 'django-tailwind[reload]'` is better.
