### ISSUE TITLE
"theme" app created in parent dir when initiated in parent dir

### ISSUE THREAD

**Issue by kennethwolters** [timonweb/django-tailwind#192]
When lets say I am in the parent dir of the django project `repo` and I execute `python django_project/manage.py tailwind init`, the `theme` app is created in the wrong spot as so:
```
repo/
├── django_project/
│   ├── django_project/
│   ├── manage.py
│   └── myapp/
├── theme/
```
However, it should be created as so:
```
django_project/
├── django_project/
├── myapp/
├── theme/
├── manage.py
```
This error is easily fixable by moving the `theme` dir into the `django_project` dir. However, I thought it is still worth reporting since this seems to be a bug.

**Comment by rajeshchaudhary007** [comment]
you should be in your project level directory. change your directory before executing command 
/repo/django_project$ python manage.py tailwind init

**Comment by kennethwolters** [comment]
Yeah inb4 I thought one shouldn't be forced to be in the right dir. But after testing it seems that even with `python repodir/projectdir/manage.py startapp testapp`, the `testapp` dir will also be misplaced so this behaviour seems inherent to `manage.py`
