### ISSUE TITLE
Tailwind CLI or nodejs?

### ISSUE THREAD

**Issue by drozzy** [timonweb/django-tailwind#199]
I thought there would be no reason to install node.js with this package. But it seems like production still needs nodejs for this to work.
Am I wrong?
I tried installing https://github.com/timonweb/pytailwindcss instead of nodejs - and still nothing.
The issue is I'm running on DO App Platform Python build-pack and they don't have nodejs. I would like to avoid making the build process more complicated. Any tips?

**Comment by timonweb** [comment]
@drozzy you still need Node.js for this package. I had plans to add Pytailwindcss support, but I just don't have time for that at the moment.
