### ISSUE TITLE
Supporting Tailwind Plugins

### ISSUE THREAD

**Issue by lysecret2** [timonweb/django-tailwind#20]
Hey, 
I wanted to try out Tailwind UI in a Django project, for that I need to include a plugin. However, I get an error when I try to run the dev server with the plugin in place.

**Comment by timonweb** [comment]
what error? please provide more details if you want to get any help here

**Comment by edgarmacas** [comment]
How could you implement a tailwind plugin for example: Tailwind CSS Custom Forms
What steps should I take, help please

**Comment by timonweb** [comment]
Just go to the generated by django-tailwind `static_src` directory and do whatever https://github.com/tailwindcss/custom-forms docs say.

**Comment by kruppy** [comment]
Hey Timon,

I tried it but it didn't work for me. I went to the static_src folder (in virtualenv) and installed it via `npm install @tailwindcss/custom-forms --save-dev` then I added the reference in tailwind.config.js.

Did I miss anything?

**Comment by timonweb** [comment]
Seems you did everything right. What do you mean by "it didn't work for me"? What's expected and what's the outcome?

**Comment by kruppy** [comment]
Unstyled Elements

**Comment by mrtrosen** [comment]
I wanted to post that I didn't have any issues adding the tailwindcss custom-forms dependencies, the steps I followed were:

1. Add the custom-forms packge to the devDependencies in theme/static_src/src/package.json file
2. Run the tailwind install django command:  #>  python manage.py tailwind install
3. Run the tailwind start django command:    #>  python manage.py tailwind start

My devDependencies in the package.json file:

  "devDependencies": {
    "tailwindcss": "^1.4.6",
    "autoprefixer": "^9.7.6",
    "clean-css-cli": "^4.3.0",
    "node-sass": "^4.14.1",
    "postcss-cli": "^7.1.1",
    "postcss-scss": "^2.0.0",
    "rimraf": "^3.0.2",
    "watch": "^1.0.2",
    "@tailwindcss/custom-forms": "^0.2.1"
  }

The styling for the forms show up without an issue.
