### ISSUE TITLE
New to both Tailwind and Django

### ISSUE THREAD

**Issue by emeidell** [timonweb/django-tailwind#21]
Hi! I was super excited to see this library because i am trying to not use Bootstrap. However, i am finding that i am lost on how to use it. Now i followed the instructions exactly but still lost. I think that is mostly due to still learning Django but might not be. 
For reference i am tying to follow along to [this tutorial ](https://www.youtube.com/watch?v=9aEsZxaOwRs). I have 2 apps. first is my accounts app and second is the newly created 'theme' app. I am lost on how i use the `base.html` in the accounts app. Should these not be shared in the way i am trying? When i try extending the `base.html` i get a "TemplateDoesNotExist" error. 
![image](https://user-images.githubusercontent.com/24320206/81896613-35399d00-9572-11ea-8c33-5b4e341c30ce.png)

**Comment by timonweb** [comment]
Hey, try to replace:

`{% extends 'theme/base.html' %}` with `{% extends 'base.html' %}`.

**Comment by emeidell** [comment]
Oh man i feel dumb. That worked great. 1 final question, `python manage.py tailwind start` does not start the whole server. So is this to be run on the side? Is this command just a python `npm start`?

**Comment by timonweb** [comment]
No worries. When an html file is placed at the top level of "templates" folder, it belongs to a global scope, i.e. no app name needs to go before it, hence the "base.html".

Re `python manage.py tailwind start`, yes it's just a wrapper around `npm start`. You can use `npm start` instead. The convenience the wrapper brings is that you don't have to cd into "themes/static_src" directory every time you want to `start` or `build`.
