### ISSUE TITLE
SASS not compiling!

### ISSUE THREAD

**Issue by iamaakashbasnet** [timonweb/django-tailwind#22]
I made a sass variable in sass file but in css file the actual sass is compiled!

**SASS**
    $primary: #333;
    .bg-primary {
        background: $primary
    }

**CSS file**
    $primary: #333;
    .bg-primary {
        background: $primary
    }

**Expected CSS file **
    .bg-primary {
        background: #333;
    }

**Comment by timonweb** [comment]
Thanks for letting me know about this. I haven't used tailwind for some time and you're the first person reported that. Fixed and pushed a fresh 0.9.0 release. The best way to upgrade your current project is to copy contents of https://github.com/timonweb/django-tailwind/blob/master/tailwind/app_template/static_src/package.json into your `theme/static_src/package.json` and run `npm install` in `theme/static_src`.

**Comment by iamaakashbasnet** [comment]
It's working now! Thanks for the fix! :D

**Comment by timonweb** [comment]
@iamaakashbasnet thanks for letting me know!
