### ISSUE TITLE
Getting node to work with Docker

### ISSUE THREAD

**Issue by lancegoyke** [timonweb/django-tailwind#25]
This is not specifically a `django-tailwind` problem, but could be a good augmentation for the documentation.

The problem I'm experiencing is that I have a Docker container for my Django project, but that container itself doesn't have `node` or `npm` available.

Again, I would imagine this requires more Docker training for myself rather than asking a package to do a bunch of extra work, but it would be definitely be helpful if the README could walk us through it.

Keep up the great work!

**Comment by timonweb** [comment]
Sorry, Docker is out of scope of this package.
