### ISSUE TITLE
Requesting for a quick installation video

### ISSUE THREAD

**Issue by AlexCsmas** [timonweb/django-tailwind#26]
Hi Tim, 

I have been having issues installing and now stuck at step 5. 

I have compared your clone and the best I can find with reference is in test. 

Kindly do a dummy's quick installation video. I think it would assist a lot.

My opinion.

Thanks

**Comment by NishantGautam023** [comment]
Yes the quick installation video would be awesome!! plz make it

**Comment by AlexCsmas** [comment]
I am currently using the CDN option and your repo keeps giving me errors. I will share my process and perharps you can advise where I might be going wrong.

**Comment by timonweb** [comment]
I don't have time now for this, sorry. Maybe in the future

**Comment by AlexCsmas** [comment]
No worries Tim, 
Completely understandable. Thanks for the feedback.
Regards.
