### ISSUE TITLE
Dependencies wrongly specified in pyproject.toml

### ISSUE THREAD

**Issue by jbajor** [timonweb/django-tailwind#27]
I just created a new django project running on Python 3.8.3 and I manage dependencies with `poetry`. I tried adding `django-tailwind` to the project with:
```
poetry add django-tailwind
```
and got the following error:
```
[SolverProblemError]
The current project's Python requirement (^3.8) is not compatible with some of the required packages Python requirement:
  - django-tailwind requires Python >=3.6,<3.9

Because django-tailwind (0.9.0) requires Python >=3.6,<3.9
 and no versions of django-tailwind match >0.9.0,<0.10.0, django-tailwind is forbidden.
So, because achsoapp depends on django-tailwind (^0.9.0), version solving failed.
```
I tried changing the Python requirement in my project from `python = "^3.8"` to `^3.7` and `^3.6`, but the only thing that allowed installation was  `python = ">=3.6,<3.9"`.

**Comment by timonweb** [comment]
@jbajor looks like it's related to this poetry issue: https://github.com/python-poetry/poetry/issues/1413 pretty weird. I could set python=^3.6 but I have no idea how do I mark it as not 3.9 using that syntax...

**Comment by jbajor** [comment]
In my project I changed `python = "^3.8"` to `python = "3.8"` and it helped. I also think that's a poetry issue. Therefore, I think this issue could be closed.

@timonweb Thanks for your help, I appreciate your work.
