### ISSUE TITLE
Where to specify individual utilities

### ISSUE THREAD

**Issue by kruppy** [timonweb/django-tailwind#28]
Hi,
following tutorials, many are declaring individual utilities after @tailwind base, @tailwind components, @tailwind utilities in the style.css.

Where do I do it in Django-tailwind? Do I then have to rebuild every time?

Thanks in advance!

BR
Thomas

**Comment by timonweb** [comment]
Hi, `django-tailwind` will generate a `styles.scss` file for you, this is your master file, put your utilities there.

**Comment by kruppy** [comment]
Thanks mate!
