### ISSUE TITLE
install validation

### ISSUE THREAD

**Issue by FrauElster** [timonweb/django-tailwind#33]
I got the following project structure:

```
/my_project
   |--my_site
     |--apps/
       |--app1/
       |--app2/
     |--common/
     |--settings/
       |--prod.py
       |--dev.py
     |--theme/   (tailwind app)
     |--urls.py
     |--asgi.py
     |--wsgi.py
    |--setup.py
    |--manage.py
    |--.flake8
    |--etc pp
```
now in my settings.py (here prod.py/dev.py) i have to install my theme as _website.theme_, the app name however is _theme_.
In the _validation.py_ of django-tailwind it checks if the app is installed, by looking for the app name (_theme_), instead of in this case _website.theme_.

Not quiet sure if my project structure is odd (but it follows a pretty common approach), or even an issue of django-tailwind (cause the 'apps.is_installed("theme")' of django returns false.

So my next approach was to rename the app (theme/apps.py) to website.theme and in settings also alter the TAILWIND_APP_NAME to 'website.theme'.

The install command now passed the "is installed"-mark, but therefore failed on the "is a tailwind app"-mark, due to __LookupError__ in djangos _apps/registry.py_ in get_app_config("website.theme").

I think I bypassed the issue by renaming the theme app back to "theme" and just returning at the "is installed"-mark. But this process makes deployment that much harder than just saying: Run 'pip install -r requirements'.

If you think this is not an issue of this project, just ignore it. I thought I mention my thoughts. ;)

Other than that, gotta admit I<3 django-tailwind. GJ man

**Comment by timonweb** [comment]
Hej, that's an interesting case, I think I'd need to dig deeper when I have time...But what's the issue with leaving it as `theme`?

**Comment by FrauElster** [comment]
Hi,

well the issue is that the tailwind/validate.py checks on line 20, if the
app is installed in settings.py.

Therefore you are using, as one would do, the apps.is_installed of djangos
core. The parameter it checks for is the TAILWIND_APP_NAME, in my case
"theme". The apps is_installed returns False on that call.
Therefore you raise a "app not installed" exception there, although in fact
it is installed.

It seems silly to me that the Django core function won't recognize it as
installed, only because it is "my_site.theme" in the INSTALED_APPS dict
instead of "theme".

So my "solution" (it is not at all, more an bypass) was to just return on
the is_installed function in tailwind/validate.py.

I hope I could help
Best regards
Moritz

**Comment by timonweb** [comment]
hm, when you updated `apps.py`, did you also update `__init__.py` of the same module with something like `default_app_config = 'theme.apps.ThemeConfig'`?

**Comment by thomasmatecki** [comment]
I think I'm having the same issue -- here is the call stack when the exception is occurring as I see it:

```
get_app_config, registry.py:157
get_app_path, utils.py:9
get_tailwind_src_path, utils.py:13
is_tailwind_app, validate.py:25
...
```

Using django 3.0, I think the issue here is that the `app_name` is being passed to `get_app_config` [here](https://github.com/timonweb/django-tailwind/blob/5720a2e6dc7b59f5ffbfc32ba1985ad097822c67/tailwind/utils.py#L9) while `get_app_config` expects the `app_label` to [perform the lookup](https://github.com/django/django/blob/6c1923029748de4a0f443260751a93c1e0ea10fa/django/apps/registry.py#L156) in `Apps` _registry_. The `app_label` [is constructed](https://github.com/django/django/blob/6c1923029748de4a0f443260751a93c1e0ea10fa/django/apps/config.py#L35) like this:

```python
self.label = app_name.rpartition(".")[2]
```
