### ISSUE TITLE
django-tailwind depends on Django<3.1

### ISSUE THREAD

**Issue by zain** [timonweb/django-tailwind#35]
The project works great with Django 3.1 but cannot be used with it. https://github.com/timonweb/django-tailwind/blob/master/pyproject.toml#L29

**Comment by AdrienLemaire** [comment]
+1, please remove the Django<3.1 requirement.

**Comment by timonweb** [comment]
Done, check the latest release on PYPI: https://pypi.org/project/django-tailwind/0.10.0/
