### ISSUE TITLE
Template syntax with Vue + Django Tailwind not working

### ISSUE THREAD

**Issue by erikvlm** [timonweb/django-tailwind#36]
I'm using Vue from a CDN, and after setting up django-tailwind, the template does not render dynamic content. I tried setting up different delimiters:

```
<div id="app">
[[msg]]
</div>
  var app = new Vue({
        delimiters: ['[[', ']]'],
        el: '#app',
        data: {
        msg: "Hello"
     }
```

In my template, all I see is [[msg]], instead of "Hello".

I also tried 
```
{% verbatim %}
{{msg}}
{% endverbatim %}
```
Without success. Do I need to configure something to have Vue templates work?

**Comment by timonweb** [comment]
Hi, sorry I have no idea, Django-Tailwind has nothing to do with how templates function. The issue you're experiencing is surely related to Django template + Vue.js combination.

**Comment by erikvlm** [comment]
Well, the existing Vue functionality broke after installing Django Tailwind :/
