### ISSUE TITLE
Preexisting Django app

### ISSUE THREAD

**Issue by deltuh-vee** [timonweb/django-tailwind#37]
How can I add django-tailwind if I already have an app created? I wasn't able to use `python manage.py tailwind init` since the app exists already.

**Comment by timonweb** [comment]
You mean the app with the `theme` name? You don't have to call it `theme`, you can call it `whatever`, for example:

`python manage.py tailwind init whaterver`

In **settings.py**:
`TAILWIND_APP_NAME = 'theme'`

**Comment by deltuh-vee** [comment]
I had already created an app using `python manage.py startapp` and I wanted to use tailwind in it without creating another app. I think I was able to work around it by manually copying over the template and files.
