### ISSUE TITLE
Two resolved issues in Win10

### ISSUE THREAD

**Issue by rbeard0330** [timonweb/django-tailwind#42]
I encountered a couple issues getting this library to work on my system, and I thought I should post them here in case they're helpful for others.

First error (running `tailwind start`):

```
Tracking file by folder pattern:  migrations

> django_tailwind@ start ***\static_src
> npm run dev


> django_tailwind@ dev ***\static_src
> watch 'npm run dev:sass && npm run dev:postcss' ./src

> Watching run
> Watching dev:sass
***\static_src\node_modules\watch\main.js:73
    if (err) throw err;
             ^

[Error: ENOENT: no such file or directory, stat '***\static_src\dev:sass'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: ***\\static_src\\dev:sass'
}
`

The fix here was modifying the dev script in `package.json` from:
```
"dev": "watch 'npm run dev:sass && npm run dev:postcss' ./src",
```
to:
```
"dev": "watch \"npm run dev:sass && npm run dev:postcss\" ./src",
```

Second error (still on `tailwind run`):

```
TypeError: node.getIterator is not a function
    at LazyResult.visitTick (***\static_src\node_modules\postcss\lib\lazy-result.js:484:33)
    at LazyResult.runAsync (***\static_src\node_modules\postcss\lib\lazy-result.js:372:30)
    at async Promise.all (index 0)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! django_tailwind@ dev:postcss: `postcss --config . --map true --output ../static/css/styles.css ../static/css/styles.css`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the django_tailwind@ dev:postcss script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

The fix here was to update `postcss-scss` to v.3.0.4.

Now, everything is working great.  Thanks!  Let me know if there's any other info you'd like.

**Comment by timonweb** [comment]
Hi @rbeard0330, thanks a lot for letting me know about these issues. I don't have a Windows machine, so I'd need someone with Windows to verify this and create a PR. It can be you. So I'm calling for help here.

**Comment by timonweb** [comment]
Current master contains those fixes, thank you for reporting them! Tomorrow I'm planing to make a `1.1.0` release.
