### ISSUE TITLE
I keep getting error on Tailwind Start command

### ISSUE THREAD

**Issue by Ladet02** [timonweb/django-tailwind#43]
I keep having troubles on tailwind installation and setup i do not know how to go about it

`node:internal/fs/utils:320 throw err; ^ Error: ENOENT: no such file or directory, scandir 'C:\Users\Lanre Adetoro\CODE\djangoProject1\osmotheme\static_src\node_modules\node-sass\vendor' at Object.readdirSync (node:fs:1044:3)`

![image](https://user-images.githubusercontent.com/75883669/103138763-ffe35900-46d5-11eb-9c22-01731f6cfc54.png)

what do you think might be the problem

**Comment by timonweb** [comment]
Hey, check the node version, it should be 12.3 or newer.
