### ISSUE TITLE
How do I use tailwindcss/forms plugin?

### ISSUE THREAD

**Issue by Shavinder** [timonweb/django-tailwind#44]
Hello,
I wish to use https://github.com/tailwindlabs/tailwindcss-forms to get my django forms to look good. How can I go about integrating this plugin ?

**Comment by justinmayer** [comment]
This project sets up Tailwind CSS, after which it's up to the developer to use it to style Django-powered web applications.

What you are looking for is likely a combination of [Django Crispy Forms](https://github.com/django-crispy-forms/django-crispy-forms) and its [Tailwind CSS template pack](https://github.com/django-crispy-forms/crispy-tailwind).

**Comment by timonweb** [comment]
@Shavinder it's up to you. All steps are listed here: https://github.com/tailwindlabs/tailwindcss-forms#installation.
