### ISSUE TITLE
"tailwind init" does not respect dotted app names.

### ISSUE THREAD

**Issue by nerdoc** [timonweb/django-tailwind#47]
when starting an app usign `./manage.py tailwind init foo` - it works flawlessly. Django says that it sort of "recommends" top level directory apps. But the directory structure of bigger projects could be more complicated. Apps are normal python packages which could be installed in any directory, e.g. in one of my projects under the `plugins/` directory.

But calling `./manage.py tailwind init plugins.foo` tells me that

    CommandError: 'plugins.foo' is not a valid app name. Please make sure the name is a valid identifier.

According to the [Django docs for AppConfig.name](https://docs.djangoproject.com/en/3.1/ref/applications/#django.apps.AppConfig.name), it is a "full Python path to the application, e.g. '**django.contrib.admin**'."

Only the label must be a single Python identifier.
So I think django-tailwind mixes up these two (I too did this in a similar library) - could you correct this?

If I create a tailwind app with `tailwind init`, and copy the static_src folder + base template manually into another app, or move that whole app directory a level deeper, and set `TAILWIND_APP_NAME="plugins.foo` - it does work, and I can use `tailwind install`.

**Comment by timonweb** [comment]
Hi thanks for the report. Feel free to fix the issue and push the PR here, I'll happily merge.

**Comment by nerdoc** [comment]
I'll try my best ;-)

**Comment by nerdoc** [comment]
Sorry, I didn't find the time and moved away to django-sockpuppet...
