### ISSUE TITLE
ModuleNotFoundError: No module named 'tailwindcalculate'

### ISSUE THREAD

**Issue by shariq1989** [timonweb/django-tailwind#49]
I followed the guide until I got down to:
`python manage.py tailwind init theme`

![image](https://user-images.githubusercontent.com/2559167/109841609-75076900-7c06-11eb-9e36-f15212260358.png)

This is on an Ubuntu machine running the latest version of Django.

**Comment by timonweb** [comment]
Hi, the error doesn't seem related to django tailwind. It looks like you have an app that's not installed, hence the error. Check what's the `tailwindcalculate` in your codebase.

**Comment by shariq1989** [comment]
@timonweb you were right!

**Comment by timonweb** [comment]
Great, thanks for confirming!
