### ISSUE TITLE
./manage.py tailwind build doesn't purge CSS

### ISSUE THREAD

**Issue by thijskramer** [timonweb/django-tailwind#51]
I have configured `tailwind.config.js` as following: 

```js
module.exports = {
  purge: [
      // Templates within theme app (e.g. base.html)
      "../templates/**/*.html",
    ],
  }
}
 ```
 
 When I run `./manage.py tailwind build`, a full 3.2 MB css file gets generated. But when I explicitly turn on purging with: 

```js
module.exports = {
  purge: {
      enabled: true,
      content: [
        // Templates within theme app (e.g. base.html)
        "../templates/**/*.html",
      ],
    }
  }
}
 ```
 Then  a stylesheet of only 10 KB gets generated, so that means that purging works and that the path to the HTML templates  is correct.

Now, the [Tailwind documentation](https://tailwindcss.com/docs/optimizing-for-production#basic-usage) says: 

> Now whenever you compile your CSS with `NODE_ENV` set to `production`, Tailwind will automatically purge unused styles from your CSS.

Does that mean that `./manage.py tailwind build` doesn't run with that environment variable turned on? And is this a bug or is this intentional behavior and should I run `./manage.py tailwind build` with the forementioned env variable? 

Thank you for your effort and I'm looking forward to a response!

**Comment by timonweb** [comment]
Hi @thijskramer, there was the bug, it's been fixed. 

Please make sure that your tailwind's package.json is inline with the latest app template: https://github.com/timonweb/django-tailwind/blob/master/tailwind/app_template_v2/static_src/package.json#L9 <- pay attention to this line, here's where we inject `NODE_ENV=production`.  I use `cross-env` for that to ensure compatibility on Windows, so you might need to install `cross-env`, check `dependencies` in the `package.json`. 

Please let me know how it went.

**Comment by thijskramer** [comment]
Ah, I've missed the change in package.json! Maybe there should be a mechanism to ensure the package.json gets updated too 🤔  When I have an idea for that I might make a PR, but for now updating the scripts section in package.json suffice. Thanks for your reply!
