### ISSUE TITLE
`tailwind start` ignoring changes in certain files

### ISSUE THREAD

**Issue by tbentham** [timonweb/django-tailwind#54]
I noticed that `tailwind start` only watches for changes to files in `./src`, therefore ignoring changes to files directly at `./` such as `tailwind.config.js`.

Would it not be better to watch `./` for changes instead of `./src`?

**Comment by timonweb** [comment]
Watching `tailwind.config.js` won't help you. If you add changes to the config file, you have to restart the process anyway.

**Comment by tbentham** [comment]
As far as I can tell from `package.json` , the `start` script only runs the `watch` command, which in turn runs all subsequent commands in response to changes. Is there something else I'm missing that would require restarting the process?

**Comment by timonweb** [comment]
yes, but for `start` script to be able to pickup changes from `tailwind.config.js`, you need to restart it. It can't watch itself and restart. `tailwind.config.js` supplies configuration for the `tailwind` command line tool. You have to restart it, so that it could pick up own configuration changes.

**Comment by tbentham** [comment]
That's strange though - I tried it just now by editing the `theme` section in `tailwind.config.js` and it seemed to pick up the change just fine. Is there something else going on under the hood?

**Comment by timonweb** [comment]
It did? Huh...well that's something new, I remember it didn't work when I tried a year ago. Sounds like good news, then indeed `tailwind.config.js` should be watched to, but if we change to `./` that would mean `node_modules` are being watched too and we don't want that. Need to check `watch` docs to see how to solve this.

**Comment by tbentham** [comment]
It might just be own set-up, I'm not certain. I'm using a virtual environment if that makes a difference.

I'll admit that using `./` is a naive approach - I guess you would have to run an additional `watch` on `tailwind.config.js` or something like that.

Anyway, thanks for your response!

**Comment by timonweb** [comment]
Improved in v2.0
