### ISSUE TITLE
Tailwind CSS JIT

### ISSUE THREAD

**Issue by rickavmaniac** [timonweb/django-tailwind#55]
Hi,

Do you intend to implement new Tailwind CSS JIT?

Thanks :)

Eric

**Comment by justinmayer** [comment]
Hey @rickavmaniac. Before filing an issue, perhaps consider checking existing issues *and* pull requests? Case in point: #52

**Comment by rickavmaniac** [comment]
Oupss I miss that one sorry.

**Comment by timonweb** [comment]
@rickavmaniac sure, I'm waiting for it to become stable. It's an experimental feature for now.
