### ISSUE TITLE
PyCharm's Tailwind CSS plugin fails to show code assistance without symlinks in project root

### ISSUE THREAD

**Issue by junctionapps** [timonweb/django-tailwind#57]
This is not an issue with django-tailwind but a note for anyone using it along with PyCharm and the [JetBrains Tailwind&nbsp;CSS plug in](https://plugins.jetbrains.com/plugin/15321-tailwind-css).

I filed a bug with JetBrains, as the intellisense/code assistance was not working for Django templates inside of the 'normal' app structure of `[project root]/app_name/templates/app_name/htmlfiles.html` which may eventually make the steps below unnecessary.

It was found that if you create symlinks to `node_modules`, `package.json` and `tailwind.config.js` in the root of the Django project (same directory as `manage.py`) to the appropriate targets under `theme/static_src` that the JetBrains official Tailwind&nbsp;CSS plug in works perfectly with the setup described in the django-tailwind's readme.

In the root of your Django project, assuming you named your django-tailwind app 'theme'
```
ln -s theme/static_src/package.json package.json
ln -s theme/static_src/tailwind.config.js tailwind.config.js
ln -s theme/static_src/node_modules/ node_modules
```
Reference to JetBrains YouTrack bug tracker:
https://youtrack.jetbrains.com/issue/WEB-50354#focus=Comments-27-4829062.0-0

**Comment by timonweb** [comment]
Thanks for the info. It looks like the Jetbrains Tailwind CSS plugin just assumes you put everything into the root folder.

**Comment by junctionapps** [comment]
Nothing to be done in django-tailwind
