### ISSUE TITLE
Unknown command: 'tailwind'

### ISSUE THREAD

**Issue by simkimsia** [timonweb/django-tailwind#58]
This is my requirements.txt

```md
## Django
django==3.2b1  # https://www.djangoproject.com/
django-extensions==3.1.0  # https://github.com/django-extensions/django-extensions

django-allauth==0.44.0  # https://github.com/pennersr/django-allauth

psycopg2==2.8.6 --no-binary psycopg2  # https://github.com/psycopg/psycopg2
dj_database_url==0.5.0 # https://github.com/jacobian/dj-database-url

django-htmx # https://github.com/adamchainz/django-htmx

## 3rd party system connectors and wrappers to call their API

### DigitalOcean

python-digitalocean==1.16.0 # https://github.com/koalalorenzo/python-digitalocean#how-to-install

### tailwind
django-tailwind # https://github.com/timonweb/django-tailwind/releases

```

and my settings.py include tailwind

![image](https://user-images.githubusercontent.com/245021/114400553-aba4ac00-9bd4-11eb-8a55-ab6b72e7e23b.png)

But  I still get unknown command. Why?

**Comment by timonweb** [comment]
Hi, what command do you try to run?

**Comment by simkimsia** [comment]
python manage.py tailwind init

**Comment by timonweb** [comment]
I have no idea why then. If you run `python manage.py` do you see the `tailwind` command in the list?

**Comment by simkimsia** [comment]
u mean `python manage.py --help` ?

no

![image](https://user-images.githubusercontent.com/245021/114552264-ff77c980-9c96-11eb-94fb-407b3f43d021.png)

**Comment by simkimsia** [comment]
nvm i was an iditio. i know why. sorry. thanks for helping I'm just upset with my own idiocy

**Comment by timonweb** [comment]
Hey no worries :) we've all been there many times ;)
