### ISSUE TITLE
'tailwind_tags' is not a registered tag library when added to base template

### ISSUE THREAD

**Issue by MarkMichon1** [timonweb/django-tailwind#59]
Hi there, I'm a bit lost during the installation process, specifically step #8:
https://django-tailwind.readthedocs.io/en/latest/installation.html

I'm using my own base template in another app, primary.html:

```
<!DOCTYPE html>
<html lang="en">
{% load tailwind_tags %}
<head>
    {% load static %}
    <meta charset="UTF-8">
    {% tailwind_css %}
    <title>Placeholder</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>
```

However, this returns the following error:
```
TemplateSyntaxError at /

'tailwind_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
```

I've been trying to figure this out for the last 45 minutes, to no avail.  `tailwind` and `theme` (the app name for tailwind) have been added to `INSTALLED_APPS`, as well as `TAILWIND_APP_NAME = 'theme'`.  All command line steps have been followed.  Would you know what the cause of this is?

Thanks for your time,

Mark

**Comment by timonweb** [comment]
It looks like you've installed `v1` of the package but followed instructions for `v2` which is in beta atm. Please read a note at the beginning of the README https://github.com/timonweb/django-tailwind#tailwind-css-integration-for-django-aka-django--tailwind--
