### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by AdrienLemaire** [timonweb/django-tailwind#6]
Sorry if release notes exist and I couldn't find them.
Could you add release notes to explain each version upgrade? this will help people understand what new features/bug fixes/ breaking change will occur by upgrading the package to the new version.

Many thanks for your work!

**Comment by AdrienLemaire** [comment]
@timonweb ping on this.
Also, I realized that upgrading django-tailwind didn't upgrade the related js packages (eg tailwindcss 1.1.2 → 1.1.3). 
I was assuming a management command to do that: `./manage.py tailwind upgrade`, but the only commands available are:
 * init - to initialize django-tailwind app
 * install - to install npm packages necessary to build tailwind css
 * build - to compile tailwind css into production css
 * start - to start watching css changes for dev

What is the proper way to update the package? This time, I'll go and manually modify the package.json file and rerun `tailwind install`.

**Comment by timonweb** [comment]
Changelog file has been added: https://github.com/timonweb/django-tailwind/blob/master/CHANGELOG.txt

As for tailwind version upgrade, for now, you're better off updating `package.json` file yourself.
