### ISSUE TITLE
I use docker to run my django, so is it okay to install node/npm inside the docker container?

### ISSUE THREAD

**Issue by simkimsia** [timonweb/django-tailwind#60]
I'm running `python:3.8.7-alpine3.12`

I use docker to run my django, is it okay to install node/npm inside the docker container?

![image](https://user-images.githubusercontent.com/245021/114564031-87170580-9ca2-11eb-8c47-d0594d5b3e75.png)

**Comment by timonweb** [comment]
Yes, why not? There are many ways to how you could do that, but the simplest one is to install node within your container's base image. If it's not Alpine, you should have no issues with installing node.

**Comment by simkimsia** [comment]
It's alpine :D `python:3.8.7-alpine3.12`

SO add via apk add?

**Comment by timonweb** [comment]
yeah try it, but Alpine is too stripped down to my experience, you might encounter issues. But try it out, maybe it'll work just fine.

**Comment by simkimsia** [comment]
```
FROM python:3.8.7-alpine3.12

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update \
    # psycopg2 dependencies
    && apk add --virtual build-deps gcc python3-dev musl-dev \
    && apk add postgresql-dev \
    # CFFI dependencies: i have no idea what these do but allauth apparently depends on them
    && apk add libffi-dev py-cffi \
    # because RUST is not new enough for the latest cryptography py package
    # see https://cryptography.io/en/latest/installation.html#alpine
    # see https://github.com/pyca/cryptography/issues/5776#issuecomment-775288041
    && apk add openssl-dev cargo \
    # for tailwind
    && apk add nodejs

# ... and so on
```

In case somebody has the same issues
