### ISSUE TITLE
How do I fit the package.json, tailwind.config.js and postcss.config.js within the context of django-tailwind?

### ISSUE THREAD

**Issue by simkimsia** [timonweb/django-tailwind#61]
I'm also simultaneously taking a course on tailwind for beginners.

the course provides a package.json amongst many other things for their starter templates.

I'm unsure how to place some of these files within the context of django-tailwind.

Can advise?

![image](https://user-images.githubusercontent.com/245021/114827651-8e9df200-9dfb-11eb-9d4c-41e7ec281af0.png)

Let's concentrate on these 3 files: tailwind.config.js, postcss.config.js, and package.json

## package.json

```
{
  "name": "beginner-tailwind-site",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "parcel src/index.html",
    "build": "parcel build src/index.html"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/chris-on-code/beginner-tailwind-site.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/chris-on-code/beginner-tailwind-site/issues"
  },
  "homepage": "https://github.com/chris-on-code/beginner-tailwind-site#readme",
  "dependencies": {
    "tailwindcss": "^1.8.0"
  },
  "devDependencies": {
    "parcel-bundler": "latest",
    "postcss-modules": "latest",
    "autoprefixer": "^9.8.6"
  }
}
```

## postcss.config.js

```
module.exports = {
  plugins: [require("tailwindcss"), require("autoprefixer")],
};
```

## tailwind.config.js

```
module.exports = {
  purge: ["src/**/*.html"],
  theme: {
    extend: {},
  },
  variants: {},
  plugins: [],
};

```

**Comment by simkimsia** [comment]
Ok, i get it now. you already have tailwind.config.js and postcss.config.js in theme/static_src

Now my question is should I switch to use parcel or use npm for all the various scripts commands?

**Comment by timonweb** [comment]
@simkimsia this package provides you with the complete Tailwind setup. If you're going to use parcel or any other config, there's no value in `django-tailwind` for you as of now.

**Comment by simkimsia** [comment]
oh that's good to hear. I'm ignorant of tailwind and stuff, so I asked. Good to know I can avoid parcel and extra dependencies using this plugin. Thank you, happy to drop this.

**Comment by timonweb** [comment]
yeah that's the main goal of the package: to not to dive into this webpack/parcel/whatever else nonsense.

**Comment by simkimsia** [comment]
> yeah that's the main goal of the package: to not to dive into this webpack/parcel/whatever else nonsense.

in the immortal words of the Aquaman character in the justice league trailer, 

MY MAN! 👊
