### ISSUE TITLE
If I use docker to run dev server for local dev env, how do I run the tailwind server?

### ISSUE THREAD

**Issue by simkimsia** [timonweb/django-tailwind#63]
Related to this comment about feedback https://github.com/timonweb/django-tailwind/issues/56#issuecomment-821051122 on the new django-tailwind v2

I saw this in the migration docs
![image](https://user-images.githubusercontent.com/245021/115011577-612b7400-9ee1-11eb-8f02-1b545493452b.png)

There's a `python manage.py tailwind start` which I suspect is meant for the jit mode. I am using jit.

but because I use docker what happens is that I just have this script that's executed as part of my docker up

```
#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset
set -o xtrace


python manage.py migrate
python manage.py runserver 0.0.0.0:8000

```

Do I write a separate script for the tailwind server as well?

**Comment by timonweb** [comment]
I haven't looked into that. I you figure it out, pls share your setup. A few thoughts:

* I'd create docker-compose with two services based on the same Dockerfile, one is for Django server, another is for Tailwind start

* for the Tailwind service, expose port 8383 and map it to 8383 on the host: "8383:8383".... and it should be fine.

**Comment by simkimsia** [comment]
I simply added one line to my start script

```
#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset
set -o xtrace


python manage.py migrate
python manage.py tailwind start &
python manage.py runserver 0.0.0.0:8000

```

This is what I saw

![image](https://user-images.githubusercontent.com/245021/115015796-cb92e300-9ee6-11eb-9eb0-72b486907db9.png)

Guess that worked?

**Comment by timonweb** [comment]
oh, nice idea btw, yes it's working!
