### ISSUE TITLE
I need to include vue3. any advice for me?

### ISSUE THREAD

**Issue by simkimsia** [timonweb/django-tailwind#64]
Sorry if this is out of scope. If need be, I'm happy to negotiate a support fee to help me with this question. I will write the code myself, but some guidance will be much appreciated.

I am using tailwindui components to build a landing page in my django 3.2 app. 

Turns out some js is required and tailwindui only supports vue 3 and react so far.

As previously mentioned, i am a total noob to tailwind and frontend. Was wondering if you have any advice for me to incorporate vue3 within the context of django-tailwind

## what the error I saw

![image](https://user-images.githubusercontent.com/245021/115137179-23505c00-a057-11eb-826a-d7f1c9f58d22.png)

Uncaught SyntaxError: Cannot use import statement outside a module for

```
{% block custom_js %}
<script>

    import { defineComponent, h } from 'vue'
    import { Popover, PopoverButton, PopoverPanel } from '@headlessui/vue'
```

## what i tried

I tried to add the vue3 as cdn in the base.html

didn't work

i added 

```
"vue": "^3.0.11",
    "@headlessui/vue": "^1.0.0",
    "@heroicons/vue": "^1.0.1"
```

inside theme/static_src/package.json

then i rerun python manage.py tailwind install

still didn't work

**Comment by timonweb** [comment]
@simkimsia pm me on Twitter.
