### ISSUE TITLE
Django-tailwind did not monitor my html files, how should I set the config 

### ISSUE THREAD

**Issue by roninee** [timonweb/django-tailwind#65]
I creat a new django project, add a sample polls app; install django-tailwind follow your documents.
When I change the Polls's html files, the webpage doesnot  refresh.
But If I change the Theme's  base.html, my Polls's webpage will refresh.
I think the Browsersync  doesnot monitor my polls templates dir, and I didn't change the tailwind.config.js and bs.config.js, Now how should I set config file.
Here is my project:
https://github.com/roninee/testcss

**Comment by timonweb** [comment]
Hi Roninee,

First of all, thanks for sharing your repo, this helped me debug the issue, you need to add one more line to `tailwind.config.js` that tracks templates in other apps:

```
'../../**/templates/**/*.html',
```

It should now work fine with your project setup.

**Comment by timonweb** [comment]
Please confirm if it helped

**Comment by roninee** [comment]
Sure，It worked very well. Thank you very much!!
