### ISSUE TITLE
for production mode, you stated just run "build" but I got errors in my server when I did that

### ISSUE THREAD

**Issue by simkimsia** [timonweb/django-tailwind#66]
![image](https://user-images.githubusercontent.com/245021/115994054-08a65600-a608-11eb-937e-758b5faf5f95.png)

I am also using Docker compose for production by the way. But I don't think that matters.

What worked for me in production was I needed to run 

`sudo docker-compose -f production.yml run --rm django python manage.py tailwind install`

Followed by 

`sudo docker-compose -f production.yml run --rm django python manage.py tailwind build`

At least that's true for the very first time.

**Comment by timonweb** [comment]
Read your error at the bottom, it says `node_modules` is missing, so that means your container has lost `node_modules` somewhere. Can't really say anything without looking at your docker-compose and Dockerfile.

**Comment by simkimsia** [comment]
I see

Should I commit package-lock.json by the way?

**Comment by timonweb** [comment]
Yes, generally it's a good idea to commit package-lock.json, since it "freezes" your dependencies and you can be sure that you have same versions everywhere.

**Comment by simkimsia** [comment]
Thank you Tim

**Comment by timonweb** [comment]
I feel like I need to create a demo setup for docker, since many folks might want to use django-tailwind in the context of Docker. If you grok that before me, feel free to share your config.

**Comment by simkimsia** [comment]
@timonweb 

> I feel like I need to create a demo setup for docker, since many folks might want to use django-tailwind in the context of Docker. If you grok that before me, feel free to share your config.

I don't mind collaborating on this.

It can also be you take the lead and I be your beta tester.

I also don't mind sharing what I have figured out so far and you can build on it.

What do you prefer? That i upload what i have so far into an open source github repo and then we continue spitball in that repo?

I'm open to this because I think selfishly it helps me get better at docker-django-tailwind stack which is always my prime motivation.
