### ISSUE TITLE
`cleancss` replacing color names where it shouldn't

### ISSUE THREAD

**Issue by tbentham** [timonweb/django-tailwind#67]
One of my custom fonts contains `Arial Black`, and when I run the `tailwind build` command, `Arial Black` gets replaced with `Arial #000`.

I've narrowed down the issue to the `cleancss` command.

**Comment by timonweb** [comment]
It's the issue with the `cleancss` not my setup. You can always get rid of the `cleancss`, just edit `package.json` and remove it from the build command.
