### ISSUE TITLE
'app_name' not in installed apps on tailwind install

### ISSUE THREAD

**Issue by isaacfink** [timonweb/django-tailwind#68]
I keep getting this error on `python manage.py tailwind install`:
`CommandError: ['frontend'] is not in INSTALLED_APPS`
frontend is the name of my app, i know for sure i have it inside my installed apps list and `TAILWIND_APP_NAME` is set to `frontend` as well

**Comment by isaacfink** [comment]
`python manage.py check` returns no errors in case it helps

**Comment by vanigupta20024** [comment]
Hey, I was thinking of passing a list as well to the TAILWIND_APP_NAME since multiple apps are using it in my Django project, any clues what should I do?

**Comment by timonweb** [comment]
You don't need to pass multiple app names there. Just your Tailwind's theme app name.
