### ISSUE TITLE
Can't set NPM_BIN_PATH  on Windows

### ISSUE THREAD

**Issue by rasulkireev** [timonweb/django-tailwind#7]
After getting info on where the npm is stored by executing `where npm` on Windows, I gotthe information that the path is located at `C:\Program Files\nodejs\npm` & `C:\Program Files\nodejs\npm.cmd`. Putting this information to `settings.py` does not do anything, I still get the 

```
CommandError:
It looks like node.js and/or npm is not installed or cannot be found.
```

I have tried the following:
`NPM_BIN_PATH = C:\Program Files\nodejs\npm`
`NPM_BIN_PATH = "'Program Files'\nodejs\npm"`
`NPM_BIN_PATH = "Program Files\nodejs\npm"`
`NPM_BIN_PATH = C:/Program Files/nodejs/npm`
`NPM_BIN_PATH = "'Program Files'/nodejs/npm"`
`NPM_BIN_PATH = "Program Files/nodejs/npm"`

Nothing seems to work. Any suggestions?
Thanks a ton in advance.

**Comment by JoshDollinger** [comment]
Hey, was having the same issues myself. Just tried `NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"` and that seemed to work for me

**Comment by timonweb** [comment]
@rasulkireev probably the answer above is the solution, I don't have Windows so can't verify.
