### ISSUE TITLE
PostCSS not triggering with Tailwind 2.2

### ISSUE THREAD

**Issue by robhafemeister** [timonweb/django-tailwind#79]
Hi,

I've been using django-tailwind with Tailwind 2.1.4 jit and it's been awesome.
Today I started a new project and I noticed the static/css/dist/styles.css was not being rebuilt when I updated my content.
After playing around with it I eventually changed "tailwindcss": "^2.1.1" in package.json to "tailwindcss": "2.1.4" , deleted the 
 node_modules folder and then ran python manage.py tailwind install and everything is working fine again.
Tailwind CSS 2.2.2 seems to be causing the problem as far as I can tell.

**Comment by timonweb** [comment]
Indeed, I'll add 2.2 support to the next version, meanwhile here are the upgrade instructions: https://django-tailwind.readthedocs.io/en/latest/migration.html#upgrading-from-tailwind-css-2-1-to-2-2

**Comment by xaitec** [comment]
I have tried this but still unable to get it to work. Will the new pip package be out soon?
