### ISSUE TITLE
error executing "manage.py tailwind start"

### ISSUE THREAD

**Issue by edgarmacas** [timonweb/django-tailwind#8]
help please when I run: **python manage.py tailwind start** I get the following error:

`C:\Users\DAVID\PycharmProjects\Tailwind\theme\static_src\node_modules\watch\main.js:73
    if (err) throw err;
             ^

[Error: ENOENT: no such file or directory, stat 'C:\Users\DAVID\PycharmProjects\Tailwind\theme\static_src\run'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\DAVID\\PycharmProjects\\Tailwind\\theme\\static_src\\run'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! django_tailwind@ start: `watch 'npm run build-postcss' ./src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the django_tailwind@ start script.
`
Is it a problem with the configuration? or django-tailwind

**Comment by timonweb** [comment]
It looks like you're running it under Windows and it has a problem finding `npm`. Do you have it installed?

**Comment by dchacca** [comment]
same error...  
1. cd theme/static_src/src  
2. npm run build-postcss
add in setting.py
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "/theme/static/"),
]

**Comment by edgarmacas** [comment]
Yes

**Comment by edgarmacas** [comment]
@timonweb I have install 'npm' and run `python manage.py tailwind install` successfully,

**Comment by reyesvicente** [comment]
Tailwind is installed

![Screen Shot 2019-12-31 at 6 43 33 PM](https://user-images.githubusercontent.com/45283313/71619091-a39e4400-2bfd-11ea-802a-2accefc856f3.png)


Getting this on my mac.

![Screen Shot 2019-12-31 at 6 42 03 PM](https://user-images.githubusercontent.com/45283313/71619035-59b55e00-2bfd-11ea-9164-f45ef5e822f7.png)

**Comment by timonweb** [comment]
@reyesvicente check https://github.com/timonweb/django-tailwind#quick-start step 2, did you do it?

**Comment by reyesvicente** [comment]
> @reyesvicente check https://github.com/timonweb/django-tailwind#quick-start step 2, did you do it?

Yes, I have that. That's why I commented on this because I got stuck on the manage.py command.

**Comment by Jordan-Rob** [comment]
@edgarmacas did you get a solution on this if so mind sharing it i've ran into the same problem

**Comment by edgarmacas** [comment]
@Jordan-Rob unfortunately not, but I work without problems in linux

**Comment by timonweb** [comment]
Hi all, this is clearly a problem with Windows, I don't have Windows so I can't check. If anyone using Windows has solved it, please share your solution here.

**Comment by reyesvicente** [comment]
> Hi all, this is clearly a problem with Windows, I don't have Windows so I can't check. If anyone using Windows has solved it, please share your solution here.

Hi, I use a mac.

**Comment by AkashV10** [comment]
for all windows users, replace the start script in package.json with following -
```json        
"start": "watch \"npm run build-postcss\" ./src"
```

@timonweb maybe you can add this in readme.

**Comment by denno9** [comment]
> 
> 
> for all windows users, replace the start script in package.json with following -
> 
> ```json
> "start": "watch \"npm run build-postcss\" ./src"
> ```
> 
> @timonweb maybe you can add this in readme.

this worked for me, thank you

**Comment by prafullit-bhattacharya** [comment]
thankyou so much i am bcoz  worried of  it from 3 days
