### ISSUE TITLE
Need help - Does this work with Jinja2 Templating engine ?

### ISSUE THREAD

**Issue by vidyanand** [timonweb/django-tailwind#80]
Unable to find any reference to get it work with Jinja2 templating engine instead of the default Django templating engine.Not sure where else to ask this question. 

Thanks

**Comment by timonweb** [comment]
No it doesn't work with Jinja, but to make it work with Jinja you just need to convert this piece of code: https://raw.githubusercontent.com/timonweb/django-tailwind/master/src/tailwind/templates/tailwind/tags/css.html

**Comment by dmwyatt** [comment]
For anyone else looking into this, I just got it set up and it seems to be working fine. If @timonweb is interested after I try it out for awhile I can probably make a PR to make this project work with jinja2.

* Add your directories containing jinja templates to `purge` in `tailwind.config.js`.
* create jinja.py somewhere
```python
#jinja.py
from django.conf import settings
from django.templatetags.static import static
from django.urls import reverse
from jinja2 import Environment
from tailwind import get_config
from tailwind.utils import is_path_absolute


def environment(**options):
    env = Environment(**options)
    env.globals.update(
        {
            "static": static,
            "url": reverse,
            "is_debug": settings.DEBUG,
            "tailwind": {
                "is_static_path": not is_path_absolute(get_config("TAILWIND_CSS_PATH")),
                "css_path": get_config("TAILWIND_CSS_PATH"),
            },
        }
    )
    return env
```

* In `settings.TEMPLATE` you need to add the environment you created above:

```python
{
        "BACKEND": "django.template.backends.jinja2.Jinja2",
        "DIRS": [BASE_DIR / "jinjatemplates"],
        "APP_DIRS": True,
        "OPTIONS": {
            # ADD THIS
            "environment": "jinja.environment",
        },
    },
```
* In your `base.html` or something add the following to `head`
```html
<link rel="stylesheet" href="{% if tailwind.is_static_path %}{{ static(tailwind.css_path) }}{% else %}{{ tailwind.css_path }}{% endif %}{% if v %}?v={{ v }}{% endif %}">
  {% if is_debug %}
    <script id="__bs_script__">//<![CDATA[
    document.write("<script async src='//HOST:8383/browser-sync/browser-sync-client.js'><\/script>".replace("HOST", location.hostname));
    //]]></script>
  {% endif %}
```
