### ISSUE TITLE
jit compiler doesn't compile

### ISSUE THREAD

**Issue by isaacfink** [timonweb/django-tailwind#81]
I chose the jit compiler and it worked perfectly until now it suddenly stopped compiling, I have to close the process and run `python manage.py tailwind start` again every time I add a new class

**Comment by timonweb** [comment]
Check if your Tailwind CSS hasn't upgraded to 2.2 automatically. If that's the case, then please follow the upgrade instructions here: https://django-tailwind.readthedocs.io/en/latest/migration.html#upgrading-from-tailwind-css-2-1-to-2-2
