### ISSUE TITLE
Delaying browser sync

### ISSUE THREAD

**Issue by skoontastic** [timonweb/django-tailwind#82]
Not an issue per se, but I was running into a `Browsersync` vs `runserver` discrepancy where `Browsersync` would refresh before `runserver` was able to reload the site. This results in a "server not found" error in the browser when `Browsersync` does its thing, which means it needs to be manually refreshed.

I added `reloadDelay: 2000,` to my `bs.config.js` file which delays `Browsersync` by 2 seconds and gives the server time to refresh itself.

Not sure if this should go into the docs or something, but thought I'd put this out there for discussion. I'd be happy to put in a pull request to the docs if you wish.

**Comment by timonweb** [comment]
Tried to reproduce the behavior but failed. What's your OS, Tailwind version and is your setup `jit` or ahead of time? And are you on Docker maybe?

**Comment by skoontastic** [comment]
Sorry, missed your reply. I'm on macOS, latest Tailwind, and JIT. Not on Docker.
