### ISSUE TITLE
tailwind cripsy form css not working.

### ISSUE THREAD

**Issue by shahriar350** [timonweb/django-tailwind#84]
I use django-tailwind with Tailwind Cripsy form. But for enabling purge, cripsy form css is not load to main compile css.
So how can i solve this problem?

**Comment by timonweb** [comment]
Sorry I have no idea. Tailwind Crispy form isn't my project I don't know how these both play together.

**Comment by timonweb** [comment]
Make sure `purge` paths are configured correctly in `tailwind.config.js`.
