### ISSUE TITLE
`purge.content` not recognised in 'bs.config.js'

### ISSUE THREAD

**Issue by tbentham** [timonweb/django-tailwind#88]
Hey,

I have additional purge options in [tailwind.config.js](https://github.com/timonweb/django-tailwind/blob/master/src/tailwind/app_template_v2/%7B%7Bcookiecutter.app_name%7D%7D/static_src/tailwind.config.js), meaning my code is formatted like this:

```js
purge: {
    content: [
        '../templates/**/*.html',
        '../../templates/**/*.html',
    ],
    options: {
        // ...
    },
},
```

As a consequence, the line `...tailwindConfig.purge` in [bs.config.js](https://github.com/timonweb/django-tailwind/blob/master/src/tailwind/app_template_v2/%7B%7Bcookiecutter.app_name%7D%7D/static_src/bs.config.js) does not work unless I change it to `...tailwindConfig.purge.content`.

Would it be possible to account for both cases?

**Comment by timonweb** [comment]
Just replace `...tailwindConfig.purge` with `...tailwindConfig.purge.content` in your `bs.config.js` and it should work just fine.
