### ISSUE TITLE
Ignore trailing space

### ISSUE THREAD

**Issue by ghost** [timonweb/django-tailwind#89]
Hi, the app should ignore the trailing space while using the `python manage.py tailwind init
`

**Comment by timonweb** [comment]
Hi, could you please specify in more details? I don't quite understand.

**Comment by abhijeet-cn** [comment]
When we ran `python manage.py tailwind init` the program asks for an app name.

I entered the name frontend with a trailing space and all config in the app was made with the trailing whitespace which I manually had to remove. This could be prevented by ignoring the space at the end.

I hope I was able to explain and btw cool library really loving the browser-sync. 

Thanks!

**Comment by timonweb** [comment]
Added in master.
