### ISSUE TITLE
I followed the instructions but python manage.py tailwind start is not working

### ISSUE THREAD

**Issue by RocketRene** [timonweb/django-tailwind#91]
Hi @timonweb I am new to django and I want to use your libary. But I always get this error 
`[nodemon] app crashed - waiting for file changes before starting... `
when running `python manage.py tailwind start` 

[https://github.com/RocketRene/django_tailwind_test](https://github.com/RocketRene/django_tailwind_test)

Do you know what I can do ?
**Thank you for your help and the libary** 

This is the full log that I get after running the command

➜ python manage.py tailwind start

> theme@2.2.0 start /Users/svenjadunger/PycharmProjects/django_tailwind_test/theme/static_src
> npm run dev

> theme@2.2.0 dev /Users/svenjadunger/PycharmProjects/django_tailwind_test/theme/static_src
> nodemon -x "npm run dev:sync" -w tailwind.config.js -w postcss.config.js -w bs.config.js -e js

[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): tailwind.config.js postcss.config.js bs.config.js
[nodemon] watching extensions: js
[nodemon] starting `npm run dev:sync`

> theme@2.2.0 dev:sync /Users/svenjadunger/PycharmProjects/django_tailwind_test/theme/static_src
> run-p dev:tailwind sync

> theme@2.2.0 dev:tailwind /Users/svenjadunger/PycharmProjects/django_tailwind_test/theme/static_src
> cross-env NODE_ENV=development tailwindcss --postcss -i ./src/styles.css -o ../static/css/dist/styles.css -w

> theme@2.2.0 sync /Users/svenjadunger/PycharmProjects/django_tailwind_test/theme/static_src
> browser-sync start --config bs.config.js

[Browsersync] Watching files...
/Users/svenjadunger/PycharmProjects/django_tailwind_test/theme/static_src/node_modules/tailwindcss/lib/jit/corePlugins.js:242
  ...Object.fromEntries(Object.entries(corePlugins).map(([pluginName, plugin]) => {
            ^

TypeError: Object.fromEntries is not a function
    at Object.<anonymous> (/Users/svenjadunger/PycharmProjects/django_tailwind_test/theme/static_src/node_modules/tailwindcss/lib/jit/corePlugins.js:242:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/svenjadunger/PycharmProjects/django_tailwind_test/theme/static_src/node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:36:43)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! theme@2.2.0 dev:tailwind: `cross-env NODE_ENV=development tailwindcss --postcss -i ./src/styles.css -o ../static/css/dist/styles.css -w`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the theme@2.2.0 dev:tailwind script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/svenjadunger/.npm/_logs/2021-08-25T12_54_08_537Z-debug.log
ERROR: "dev:tailwind" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! theme@2.2.0 dev:sync: `run-p dev:tailwind sync`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the theme@2.2.0 dev:sync script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/svenjadunger/.npm/_logs/2021-08-25T12_54_08_726Z-debug.log
[nodemon] app crashed - waiting for file changes before starting...

**Comment by timonweb** [comment]
Hi @RocketRene,

It's seems like you're running on the old Node.js version. Could you run `node -v` command in your terminal and tell me what it shows? It should be at least `14`.

**Comment by RocketRene** [comment]
Hi Tim ! Thank you for your fast response ! I have updated node and it works now ! Thank you very much !

**Comment by timonweb** [comment]
Great, I'm glad it works!
